### ISSUE TITLE
Error when playing "Bonobo : Linked (Official Audio)" (0W-a11Tdk7Y)

### ISSUE THREAD

**Issue by natumbri** [natumbri/mopidy-youtube#122]
@jaminh has reported that mopidy-youtube 3.0a1 threw the following error when trying to play [Bonobo : Linked (Official Audio)](https://www.youtube.com/watch?v=0W-a11Tdk7Y):

>2020-01-16 19:05:36,316 INFO [25468:YouTubeBackend-3] pykka: Exception returned from YouTubeBackend (urn:uuid:f5326b13-5ac9-4889-a394-78943778fdad) to caller: Traceback (most recent call last): File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop response = self._handle_receive(envelope.message) File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive return callee(*message.args, **message.kwargs) File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/backend.py", line 196, in lookup name=video.title.get().replace(";", ""), AttributeError: 'NoneType' object has no attribute 'replace'
>2020-01-16 19:05:36,397 ERROR [25468:Core-8] mopidy.core.library: YouTubeBackend backend caused an exception. Traceback (most recent call last): File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling yield File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 217, in lookup result = future.get() File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get _compat.reraise(*self._data['exc_info']) File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise raise value File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop response = self._handle_receive(envelope.message) File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive return callee(*message.args, **message.kwargs) File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/backend.py", line 196, in lookup name=video.title.get().replace(";", ""), AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by jaminh** [comment]
When I got that error I attempted to play the uri `yt:https://www.youtube.com/watch?v=0W-a11Tdk7Y` through the streams page on the musicbox_webclient. I currently have mopidy running on a raspberry pi 3 with the following versions installed:
`asn1crypto                0.24.0    
beautifulsoup4            4.8.2     
bs4                       0.0.1     
cachetools                4.0.0     
certifi                   2018.8.24 
chardet                   3.0.4     
cryptography              2.6.1     
entrypoints               0.3       
idna                      2.6       
keyring                   17.1.1    
keyrings.alt              3.1.1     
Mopidy                    3.0.1     
Mopidy-Local              3.0.0     
Mopidy-MPD                3.0.0     
Mopidy-MusicBox-Webclient 3.0.1     
Mopidy-Youtube            3.0a1     
pafy                      0.5.5     
pip                       18.1      
pycrypto                  2.6.1     
PyGObject                 3.30.4    
Pykka                     2.0.2     
python-apt                1.8.4     
pyxdg                     0.25      
requests                  2.21.0    
SecretStorage             2.3.1     
setuptools                40.8.0    
six                       1.12.0    
soupsieve                 1.9.5     
tornado                   5.1.1     
uritools                  2.2.0     
urllib3                   1.24.1    
wheel                     0.32.3    
youtube-dl                2019.12.25
`
Here is the configuration I am using:
`[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy

[logging]
config_file = /etc/mopidy/logging.conf
debug_file = /var/log/mopidy/mopidy-debug.log

[local]
media_dir = /home/pi/Music
data_dir = /var/lib/mopidy/local
scan_timeout = 2000
scan_flush_threshold = 100
scan_follow_symlinks = true
excluded_file_extensions =
	.directory
	.html
	.jpeg
	.jpg
	.log
	.nfo
	.png
	.txt
	.ini

[file]
media_dirs = /home/pi/Music
excluded_file_extensions =
	.directory
	.html
	.jpeg
	.jpg
	.log
	.nfo
	.png
	.txt
	.ini

[m3u]
playlists_dir = /var/lib/mopidy/playlists

[mpd]
hostname = ************

[http]
hostname = ************

[musicbox_webclient]
enabled = true
musicbox = true
websocket_host =
websocket_port =
on_track_click = PLAY_ALL
`

**Comment by natumbri** [comment]
Thanks @jaminh - unfortunately, I can't seem to replicate the problem here.  

I have some slightly different versions of various libraries installed, but even when I rolled back to the same versions you have, the track played just fine.  

Are you able to consistently replicate this error by playing the track? Or is it intermittent?

**Comment by jaminh** [comment]
I added a log statement for "data" in youtube.py after line 186 and I got:
`2020-01-18 20:02:20,500 ERROR [12529:Thread-14] mopidy_youtube: Data: {'items': [{'id': '3NiEikrHV7c', 'contentDetails': {'duration': 'PT8M26S'}, 'snippet': {'title': "How To Check and Fill Your Vehicle's Fluids", 'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/3NiEikrHV7c/default.jpg', 'width': 120, 'height': 90}}, 'channelTitle': "AdO'Reilly Auto Parts"}}]}`
I can confirm that it is happening consistently with that particular video (or any of the official Bonobo videos it seems). I was able to get some other videos to play. If there is any other troubleshooting you want me to do let me know.

**Comment by natumbri** [comment]
So weird. I'll look into it further.  

It would be good if you could save the result that is generated at line 25 of youtube_bs4api.py and put it somewhere I can grab it. That is the webpage that it downloads, before processing.

**Comment by jaminh** [comment]
Hopefully this works https://gist.github.com/jaminh/85aaff3607becefe017f0946938ec4bb

**Comment by natumbri** [comment]
Perfect! And this suggests that the problem is related to #124 

Specifically:
>The list_videos and list_playlists functions in the bs4API class also assume that the relevant search result will always be the first search result. This is a pretty strong assumption and is pretty hacky.

While this assumption may hold, as it turns out, the list_videos function might not actually always return the first search result. In your case, the list_videos function seems to be trying to return an advertisement that occurs in the page *before* the first search result. 

Should be pretty straightforward to fix. 

TBQH, I don't use the lookup function much (at all, really) so it is not that surprising that the bug has come up there - thanks for spotting it, reporting it and assisting to resolve it!

Cheers
Nik

**Comment by jaminh** [comment]
I wasn't trying to use the lookup function so while there may be a bug in those functions I think there is a logic error somewhere that is causing it to do a lookup when it should just be playing the URI that was provided? Maybe it is a problem with the musicbox_webclient but since it was working with the old version of mopidy_youtube that makes me think the issue is in the new version. I'll try looking through the code to see if I can find anything but if I am just misunderstanding what should be happening let me know.

**Comment by jaminh** [comment]
Maybe the question I should be asking is, how do I play a youtube URI without the lookup function being called?

**Comment by natumbri** [comment]
Out of interest, what happens if you switch to using the regex based API (instead of the bs4 based one)?

You could make this switch by uncommenting lines 79-80, and commenting lines 83-84, in backend.py

**Comment by natumbri** [comment]
The `lookup` function takes a uri and returns a mopidy `Track`. If you pass a uri to `lookup` and the `Track` information hasn't been loaded, `lookup` calls `list_videos` to retrieve that information.

I usually get my uris by running `search`. A search retrieves all the information needed for a mopidy `Track` so `lookup` never needs to call `list_videos`.

I think.

**Comment by natumbri** [comment]
Try the new [fix/issue-122 branch](/natumbri/mopidy-youtube/tree/fix/issue-122).
Didn't have time to test it much, so may not work, but see how you go.

**Comment by jaminh** [comment]
Using your fix branch as is resulted in the same error as before. It played successfully using the regex based API though.

**Comment by natumbri** [comment]
Any reason you can think of that explains why YouTube is treating your setup as a "handheld", and returning the mobile page for search results? (See line 25 in your gist.)

**Comment by jaminh** [comment]
I use youtube from my phone fairly often, perhaps it associated that profile to my IP address for some reason? I haven't done anything knowingly to set it to prefer mobile or anything like that. If there are any changes to the bs api you want me to test let me know, I have been using the regex API in the meantime. Thank you for all your help on this.

**Comment by natumbri** [comment]
I've had closer look at this and updated [fix/issue-122 branch](/natumbri/mopidy-youtube/tree/fix/issue-122).

It looks to me like there is a `</script>` tag missing at line [646] of your gist, with the result that everything from that line, to the end of line [935] is regarded by BeautifulSoup as being inside a `<script>` tag. I don't think that was intended.  

To fix the problem, I've inserted some code to search for the first `<div>` tag that occurs inside each `<script>`, and to insert a `</script>` tag immediately before that `<div>`.  My thinking is that there shouldn't be `<div>` tags in scripts; the script should have ended before the `<div>` tag appears.  This is pretty hacky, but given the html seems to be broken, I didn't really know what else to do!

It also looks like the version of the search results you are getting include advertisements that look (to my script) like search results - I've inserted a line to remove them.

Anyway, if you feel like it, please test out the fix and see if it now works for you.  

Thanks again for your assistance with this.

**Comment by jaminh** [comment]
I tried out your updated branch and it looks like everything is working now. Thank you very much for all of your work on this. If there is ever any other testing you would like extra help with let me know.

**Comment by natumbri** [comment]
Thanks for testing and getting back to me. I'll merge it in and close the issue. Also good to know the regex backend works as a last resort.

**Comment by BrainStone** [comment]
I'm also running into this issue, even after reinstalling from develop. (``python3 -m pip install https://github.com/natumbri/mopidy-youtube/archive/develop.zip``)

That's the log I get:

```
INFO     [Thread-64] mopidy_youtube session.get triggered: list_videos (experimental)
INFO     [YouTubeBackend-7] mopidy_youtube youtube LibraryProvider.lookup "youtube:video/Ellie Goulding - Lights (Fytch Remix).B3WMlT7wXg0"
ERROR    [Core-10] mopidy.core.library YouTubeBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/local/lib/python3.7/dist-packages/mopidy/core/library.py", line 217, in lookup
    result = future.get()
  File "/usr/local/lib/python3.7/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/local/lib/python3.7/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/backend.py", line 196, in lookup
    name=video.title.get().replace(";", ""),
AttributeError: 'NoneType' object has no attribute 'replace'
[youtube] B3WMlT7wXg0: Downloading webpage
```
