### ISSUE TITLE
Correct URI's for youtube videos

### ISSUE THREAD

**Issue by Thomas-Sparber** [natumbri/mopidy-youtube#126]
First of all thank you very much for the great project I really appreciate your effort.
My post should just be a reference for anybody else who is having the same problem as I had, maybe you could also update the documentation a bit.

My problem:
--------------

I added the youtube urls as it is described in the documentation, e.g.

    yt:https://www.youtube.com/watch?v=RPfFhfSuUZ4

Unfortunately I always had the following error when executing

    service mopidy status

or

    sudo journalctl -u mopidy

Error:

    mopidy-youtube Backend translated URI to None

Solution
---------

After googling a while and having a look at the following posts i came up with a solution:

https://github.com/natumbri/mopidy-youtube/issues/21#issuecomment-334339959

The solution is to use the following syntax for youtube videos:

    youtube:video/.<youtube video id>

So the following url

    yt:https://www.youtube.com/watch?v=RPfFhfSuUZ4

becomes to

    youtube:video/.RPfFhfSuUZ4

**Comment by natumbri** [comment]
Thanks for your comment. Are you using Mopidy v3.0? 

A uri in the form
```
yt:https://www.youtube.com/watch?v=RPfFhfSuUZ4
```
should work. I'll try this uri when I'm home, but my expectation is that it will work.

**Comment by Thomas-Sparber** [comment]
Yes I am using mopidy 3.0.1

This is the code from mopidy_youtube/backend.py, for me it is clear that only `youtube:video/` works

    def translate_uri(self, uri):
        logger.info('youtube PlaybackProvider.translate_uri "%s"', uri)
        
        if "youtube:video/" not in uri:
            return None
        
        try:
            id = extract_id(uri)
            return youtube.Video.get(id).audio_url.get()
        except Exception as e:
            logger.error('translate_uri error "%s"', e)
            return None

Also, I didn't find out yet how to play youtube playlists. It is not too important but would be nice

**Comment by natumbri** [comment]
Sorry @Thomas-Sparber we must be talking about different things. I thought you were talking about adding a track to the queue for mopidy to play - that is done by the `lookup` function in the `YouTubeLibraryProvider` class. That function supports adding uris in the form:
```
[yt|youtube]:<url to youtube video>
[yt|youtube]:<url to youtube playlist>
[yt|youtube]:video/<title>.<id>
[yt|youtube]:playlist/<title>.<id>
```
`lookup` is the function that is called, for example, when you put a yt: uri (of any kind) into the `play stream` box in the musicbox-webclient.

The function you have identified - `translate_uri` in the `YouTubePlaybackProvider` class - is called by mopidy when it has the mopidy uri of a track that it wants to play and it needs the real uri (ie. the url) of the audio file to play.   

I'd be interested to know how you are managing to send a uri in the form `yt:www.youtube.com/watch?v=` to `translate_uri`.  Which client are you using? Or did you write something yourself?

**Comment by Thomas-Sparber** [comment]
Ah ok now I also understand! :-) Sorry for the confusion!

What I do is I put links like `youtube:video/.vwSRqaZGsPw` in an m3u file and play it using e.g. moped

**Comment by natumbri** [comment]
Oh right - that makes sense! Yes, mopidy playlists should contain proper mopidy uris, which, for the mopidy-youtube extension means
```
[yt|youtube]:video/<title>.<id>
```
That is the intended behavior.

Would it be useful to be able to reference a YouTube playlist in a mopidy playlist?

**Comment by Thomas-Sparber** [comment]
OK I understand!

Yes, for me it makes sense altough it is not too important. Referencing youtube playlists in mopidy playlists has the advantage that I don't need to manage the playlist. Every song changes on youtube are "automatically updated" into the mopidy playlist.

But this feature is not important at all. I minor enhancement if you have time for it... :-)

**Comment by natumbri** [comment]
Actually, on second thoughts, I think it is sufficient that you can add a youtube playlist by queuing them up with a uri in the form `[yt|youtube]:<url to youtube playlist>` or `[yt|youtube]:playlist/<title>.<id>`.  On that basis, I'm not going to try to change how the extension handles a YouTube uri that it gets from a mopidy playlist.
