### ISSUE TITLE
Cannot use custom youtube API key

### ISSUE THREAD

**Issue by Dzordzu** [natumbri/mopidy-youtube#130]
## Error log
```
ERROR    2020-01-31 22:10:59,984 [10783:YouTubeBackend-3] mopidy_youtube
  Failed to verify YouTube API key, disabling API
INFO     2020-01-31 22:10:59,984 [10783:YouTubeBackend-3] mopidy_youtube
  using bs4API
```

**Comment by natumbri** [comment]
Are you sure your key works? Last time someone complained about this, it turned out to be a problem with their key...

**Comment by Dzordzu** [comment]
Well. It's strange. Sometimes it works, sometimes it fails. It just looks like a random error. Dunno what happens

**Comment by Dzordzu** [comment]
And it can be a reason of the #129. After several trials (and changes in code I've risen the limit) I've managed to get it to work. And as in this issue - it happens from time to time

**Comment by Dzordzu** [comment]
I will try to reinstall mopidy. Maybe my installation is corrupted.

**Comment by natumbri** [comment]
@Dzordzu can I close this issue now?
