### ISSUE TITLE
Cache metadata of videos, maybe even the audio itself

### ISSUE THREAD

**Issue by BrainStone** [natumbri/mopidy-youtube#131]
Since I have the tendency to listen to the same videos again and this plugin keeps downloading metadata every time as well as the audio, I think it would make sense to cache at least the metadata, if not metadata and audio.

Ideally you could turn each cache on and off individually and specify a cache dir for each one.

If implemented I'd recommend that the metadata is cached by default. Because it doesn't need much storage space and would provide a noticable speed up.

**Comment by natumbri** [comment]
Okay - I don't see much benefit in cached metadata, given that (other than for the actual url for the youtube file) it is retrieved pretty quickly; but I can see how there might be advantages to caching the actual audio.  If you're still interested, on that basis,  try this: [feature/cache](/natumbri/mopidy-youtube/tree/feature/cache)

Config option required:
```
allow_cache = true
```

Basically untested; feedback appreciated.

**Comment by BrainStone** [comment]
Not sending a HTTP request is always a good thing. Especially when there are rate limits. And even more so if that data is being queried. I remember very slow loading times with playlists full of YouTube videos.

**Comment by natumbri** [comment]
Thanks @BrainStone - I just can't see how to effectively implement further caching of metadata.  Are you interested in testing the new branch?  If not, I'll close this issue.

**Comment by BrainStone** [comment]
I would but sadly I currently don't use mopidy anymore. (nor any other similar things)

**Comment by natumbri** [comment]
Thanks for letting me know.

**Comment by AndreKR** [comment]
I have been testing this feature and it works great. It's a bit confusing that it will *first* cache the whole song and mopidy is unresponsive in that time (can't even change the volume), but once the song is in the cache it works much better than before: It starts instantly and even seeking works. :+1:

**Comment by natumbri** [comment]
@AndreKR I'm thinking about how to fix up the issue where it first caches the whole song and everything freezes, and then it starts working once the song is in the cache.  I've made a [new branch](https://github.com/natumbri/mopidy-youtube/tree/fix/start-playing-while-caching) here for testing out ideas.  If you're interested, have a go and let me know your feedback.

Cheers,
Nik
