### ISSUE TITLE
[PiDi/ST7789/pirate-audio - related] Screen not updating with current track on track change

### ISSUE THREAD

**Issue by TrollDecker** [natumbri/mopidy-youtube#133]
Bear with me here, because while it relates to (probably) PiDi and the Pimoroni pirate-audio screen, I've narrowed the problem down to playback YouTube videos using this plugin, so I suspect something is missing here?

Basically, when I change tracks from one YouTube video to another, the display on the pirate-audio doesn't get updated until I press a button on the thing or change to a non-YouTube track. I've tried playing stuff from other sources and even switching from said other source to a YouTube track, and the update happens without a hitch. It's only when switching between a currently-playinng YT video and another.

**Comment by natumbri** [comment]
Thanks for the report - interesting. I'm not familiar with the PiDi or the pirate audio screen. What information is displayed? I'm guessing the thumbnail and elapsed time - is that right? I wonder if there are any other examples of this using different software/hardware - it maybe that there is, but no one's noticed yet... 

I'll think further on where to from here...

**Comment by TrollDecker** [comment]
Sorry for the late response, combination of day-long headaches and personal commitments got in the way. 

Regarding the kind of info that's displayed, it typically shows the artist and album at the top, the track name in the middle, a volume meter below that and a track progress bar at the bottom, with some button labels around the sides. It shows deliberately blurred album art behind that. In the case of this plugin, the artist and album are set as the channel name and "YouTube Video".

I eventually found that the problems I was running into aren't actually restricted to this plugin, and it turns out that PiDi was falling over upon running into a `NoneType` where it was expecting specific types at various points. In this plugin's case, it was keeling over trying to handle what I can guess is a non-existent album art image?

I've more detail here: https://github.com/pimoroni/mopidy-pidi/issues/9

**Comment by natumbri** [comment]
Thanks for the extra info. 

I'm a bit suspicious about he way the YouTube extension handles cover art. When mopidy moved to Python 3 the deprecated way of handling art was finally retired. I made changes to the YouTube extension necessary to get it working, but I didn't spend much time really understanding how it works or thinking about if what I did was particularly robust. 

[I think] there should be album art for every YouTube video - it's surprising that a `NoneType` is ever returned... I'll have a closer look at this when I get a chance.

Cheers!

**Comment by Gadgetoid** [comment]
@TrollDecker thanks for raising this. I'm still relatively new to the world of Mopidy so my plugin efforts may not be the most finessed.

I wonder if I should handle a `NoneType` in Mopidy PiDi a little bit more gracefully in any case? It certainly couldn't hurt.

**Comment by Gadgetoid** [comment]
It looks like album art might, indeed, be the issue here. Not so much because it's missing, but because the `width` and `height` values are set to `None`. A quick dive into the Mopidy API suggests this might be valid (not that I fully understand what a `fields.Integer()` actually does internally):

https://github.com/mopidy/mopidy/blob/8e789809182b5a52dcbd3626bcd2ec906af7ce8c/mopidy/models/__init__.py#L93-L108

I'll add a fix to handle this gracefully.

**Comment by TrollDecker** [comment]
Seems to be working like a charm now. :slightly_smiling_face: :+1:

**Comment by Gadgetoid** [comment]
Whew! Thank you for letting me know, and thanks for your input!

**Comment by natumbri** [comment]
Sounds like this can be closed? Out of curiosity, are you using the mopidy-youtube extension with a YouTube api key?

**Comment by TrollDecker** [comment]
Nope, not at all. :open_mouth:
