### ISSUE TITLE
Search a specific video using Mopidy Iris

### ISSUE THREAD

**Issue by lealoureiro** [natumbri/mopidy-youtube#136]
Hello,

Thanks for your excellent work.

There is a way in Mopidy Iris to search for a specific Youtube video like this:

yt:http://www.youtube.com/watch?v=Njpw2PVb1c0

Kind regards,
Leandro

**Comment by natumbri** [comment]
Hi @lealoureiro - did you work this out? I'm not familiar with the it is frontend, but the search functionality of mopidy-youtube is pretty basic, so maybe not. Have you tried ```"Njpw2PVb1c0

**Comment by roitto** [comment]
I'm having some issues with the search too. Tried with iris, mpc and ncmpcpp. Nothing is found. when i use yt:*youtube url*

Does the mopidy-youtube support searching youtube videos using video title names?

Searching stuff only writes `mopidy[10092]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'uri': ['my test']}"` in to the log.

**Comment by lealoureiro** [comment]
Hello! 

Yes I'm manage to find it. In fact is not when you searching but you when you add uri to "Now Playing" queue.  

I would like to have the same but for SoundCloud.

Thanks!

**Comment by natumbri** [comment]
Thanks @lealoureiro.  @roitto does that help you?
