### ISSUE TITLE
Getting a 403 from google video when trying to play youtube after a while

### ISSUE THREAD

**Issue by lealoureiro** [natumbri/mopidy-youtube#138]
hi Guys,

I'm not able to play Youtube videos after a while in Mopidy, other sources of media work fine but only YouTube starts failing. After restart the entire Mopidy it starts working again.

I see something strange on the logs:

Apr 10 13:14:56 music-player mopidy[2565]:   Got ERROR bus message: error=GLib.Error('Forbidden', 'gst-resource-error-quark', 15) debug='gstsouphttpsrc.c(1431): gst_soup_http_src_parse_status (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin8/GstSoupHTTPSrc:source:\nForbidden (403), URL: https://r1---sn-5hne6nsk.googlevideo.com/

What it can be?

Thank you,
Leandro

**Comment by natumbri** [comment]
Thanks @lealoureiro - that's a new one for me! The first step to solving it is to make it reproducible.

Have you got the latest versions of mopidy, mopidy-youtube and youtube-dl? Also, how do you have modipy-youtube configured? Finally, is the problem with all YouTube videos or just select ones?

**Comment by lealoureiro** [comment]
the versions I'm using:
Mopidy: 3.0.2-1
Mopidy-Yotube: 3.0
youtube-dl: 2020.3.24

Mopidy-Youtube Configuration:
[youtube]
enabled = true
youtube_api_key = xxxxxxxxxxxxx
#threads_max = 16
#search_results = 15
#playlist_max_videos = 20
api_enabled = true

The problem also occurs when I'm not using API mode.

It happens with all youtube videos from the moment it starts happening.

**Comment by natumbri** [comment]
Thanks - versions and config seem all fine, so that's good.  

My next question was going to be about using the other mode in modipy-youtube, but you've answered that, too.  

It is interesting that mopidy-youtube is getting as far as triggering gst - I guess that means all the search/list/retrieve url stuff is working.

Maybe it's an interaction between the mopidy-youtube extension and another extension you have installed? Which other ones do you use?

**Comment by lealoureiro** [comment]
i have quiet a few:
Mopidy-Iris where a i face the problem.
Mopidy-SoundCloud
Mopidy-TuneIn
MopidyYoutube

and the core ones

**Comment by natumbri** [comment]
Could you see if the problem happens when:
- Mopidy-SoundCloud is disabled
- Mopidy-TuneIn is disabled
- both are disabled
I don't imagine it is iris - unless, perhaps it is caching something...? - and the core ones work fine for me.
Are you behind a proxy of any kind?

**Comment by lealoureiro** [comment]
Hello,

Nope, I'm not using a proxy, server directly connected to internet.

Also fails when i have TuneIn and Soundcloud plugins disabled.

**Comment by natumbri** [comment]
Ok. What about when you're using a different frontend?

**Comment by lealoureiro** [comment]
Which one you suggest?

**Comment by natumbri** [comment]
If you're happy to give it a go, I'd say start with the [musicbox webclient](https://mopidy.com/ext/musicbox-webclient/) which is pretty basic, but stable and functional.

**Comment by lealoureiro** [comment]
also get same issue with musicbox, 403 from youtube URL

**Comment by natumbri** [comment]
Ok - thanks for narrowing it down; I'll try to replicate overnight. If I can, hopefully we can find a solution!

**Comment by natumbri** [comment]
youtube-dl caches some things (in ``/var/lib/mopidy/.cache```) that seem to muck playback up - does passing ```"cachedir": False``` to YoutubeDL fix this?

**Comment by lealoureiro** [comment]
where I can set the parameter?

**Comment by natumbri** [comment]
Sorry - it requires editing the code. If you are comfortable to do that, in the file ```youtube.pl``` after line x ( ), insert ```"cachedir": False```.

I'll be making that change to the code in any event at some point - I don't think youtubeDL caches anything particularly helpful and turning it off fixes a  problem that I've been experiencing (which may be related to your problem).

**Comment by lealoureiro** [comment]
I'm using a Docker image is a bit more complicated to change, maybe i can fork the plugin and install from the source.

How do I install from a local git repository?

**Comment by natumbri** [comment]
I don't know anything about Docker images.  Do you/can you use pip to install and update things?  If so, maybe something like:
```
$ sudo python3 -m pip install -U git+https://github.com/natumbri/mopidy-youtube.git@feature/autoplay
```

**Comment by lealoureiro** [comment]
Same issue :(

Just woke up, mopidy was idle, i tried to play a youtube set and got error:

May 02 11:06:37 leandro-homeserver docker[20082]:   Got ERROR bus message: error=GLib.Error('Forbidden', 'gst-resource-error-quark', 15) debug='gstsouphttpsrc.c(1431): gst_soup_http_src_parse_status (): /GstPlayBin:playbin0/GstURIDecodeBin:uridecodebin11/GstSoupHTTPSrc:source:\nForbidden (403), URL: https://r2---sn-5hne6ns6.googlevideo.com/videoplayback?expire=1588394003&ei=s6OsXvm_BJKigQfU54EI&ip=62.163.247.87&id=o-ABO91nMTVHYjtZqXv-4EXTE7gctRdlkLfOF3Hi6ZGMVs&itag=251&source=youtube&requiressl=yes&mh=rS&mm=31%2C29&mn=sn-5hne6ns6%2Csn-5hnekn76&ms=au%2Crdu&mv=m&mvi=1&pl=17&initcwndbps=1498750&vprv=1&mime=audio%2Fwebm&gir=yes&clen=65245912&dur=3860.901&lmt=1587230675321404&mt=1588372290&fvip=2&keepalive=yes&c=WEB&txp=5531432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cvprv%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=ALrAebAwRQIgY42iv_i9JAxjh3i_iAoIFNf9vsAPkHmStSbIvmTH4rsCIQD2B3rsE14hdS1GUvqn6lln8bCvHRO7cVZefBCmxNEjtw%3D%3D&sig=AJpPlLswRAIgJpQVGKdpGddDnUvJSC0kN1p85UkZRkCGtdecpJvfatMCIHkRy4mgy4Fd8wdCYx-Jb_8QIA2v3zC7uuokCqUDJdT-&ratebypass=yes, Redirect to: (NULL)'

Mopidy installation docker I'm using:
[Docker Image](https://github.com/lealoureiro/mopidy-docker/blob/master/Dockerfile)

**Comment by natumbri** [comment]
Ok - this has me stumped. I'm going to use the docker to set it up on a spare machine I have and see if I can replicate. Never tried docker before, so hopefully it all goes ok!

@lealoureiro I really appreciate you taking the time to have a go at all my suggestions - hopefully by using your docker image I can replicate the problem and we can work out how to fix it!

**Comment by lealoureiro** [comment]
You welcome! I just like to help maybe even near future i will try to code as well as my python skills allow :)

In github page of that docker file you have a bit more information how to run the image

The command I use:
`docker run --name mopidy --user {uid}:{guid} --network="host" -v {your-mopidy-data-config-folder}:/data/mopidy -v {your-local-music-folder}:/Music {docker-image-name}`

**Comment by natumbri** [comment]
@lealoureiro - apologies, I haven't gotten around to this; I have made a number of other changes though, some of which may be related to the problem.  Would you mind trying again with the current develop branch?

**Comment by lealoureiro** [comment]
@natumbri Thanks for your message!

At moment I'm living in the home that i have Mopidy installed, but once I'm back in a week i will test and let you know! thanks a lot!

**Comment by lealoureiro** [comment]
hello!

being tested so far but sometimes i still get same error. Might be YouTube denying some calls due to usage?

**Comment by natumbri** [comment]
A lot has changed since this was opened; if it is still a problem, please open a new issue.
