### ISSUE TITLE
Make 3.0 a "real" release

### ISSUE THREAD

**Issue by julidau** [natumbri/mopidy-youtube#143]
Hello there, 

this might seem like a stupid request, but could you maybe tag 0ff74f5fb7e1db6a1d94e99b70c0ca9b0cadcaf0 as the 3.0 release?

I am currently maintaining the mopidy-youtube  packages in the [Arch linux User repository](https://aur.archlinux.org/packages/mopidy-youtube/) and since they ditched python2-pykka i can't update the package to the last python2 release. 

I _could_ update the package to 3.0 but would like to avoid hardcoding the commit hash...

**Comment by natumbri** [comment]
No worries! I've tagged a v3.0 release - let me know if you need anything else!

**Comment by julidau** [comment]
ok, i have upgraded the package accordingly. 

Thank you for tagging 👍

**Comment by natumbri** [comment]
@julidau - question for you: I've been having problems with wrong versions of the youtube-dl dependency being installed through a package manager, rather than pip. See #144 towards the end.

I would like to specify a version of youtube-dl. I'm not familiar with AUR, but, assuming youtube-dl is available as a package through AUR, how are dependency conflicts dealt with (eg. if I specify a version of youtube-dl that is newer than the package version)?

**Comment by julidau** [comment]
Edit(after rereading your question): specifying a required version newer then the one provided from the official package repos will brick the package until the dependency is upgraded to the version required. However the latest youtube-dl version is already in the package repository, so...

Long answer:

Since Arch linux is rolling release you can always get the latest release for packages only. You can however specify a minimum version as well as a maximum version supported for your package dependencies.

In case the version installed is older then the one specified, it will prompt the user to update said package.

In case a package requires a version of one dependency to be lower then the one installed however, it will abort installing (or will stop updating). [Here](https://bbs.archlinux.org/viewtopic.php?id=193773) is quick example of what happens in that case.

Since #144 seems to be about the notoriously outdated debian and ubuntu packages, i could specifiy a minimum version for you. 

I hope i explained that satisfactorily...

Regarding the youtube-dl dependency: the aur is for normal user packages. Youtube-dl is packaged by users with elevated permissions and does not come from the aur, it is provided by the official repositories. One can also choose to go more "cutting edge" by installing youtube-dl-git, which compiles the package from source (as the name implies). the packet manager will however prefer the normal packages from the official repo. You can see all dependencies being listed on the [aur page](https://aur.archlinux.org/packages/mopidy-youtube/) for the mopidy-youtube package with links for the possible candiate packages.

**Comment by natumbri** [comment]
Thanks so much @julidau - that is very useful for me.

**Comment by julidau** [comment]
@natumbri glad i could help 😄

**Comment by julidau** [comment]
i just reread #144 and wanted to add that youtube-dl maintainers themself have gotten the "old version issues" due to outdated ubuntu (and probably debian) packages. 

Its also know for a bit longer now ^^

https://bugs.launchpad.net/ubuntu/+source/youtube-dl/+bug/1529647

**Comment by natumbri** [comment]
Thanks for the link - yes, it looks like a pretty long-standing issue. I agree with the comments to the effect that if the package will not be kept up to date, it would be better to not have it at all. The older versions just break things.
