### ISSUE TITLE
YouTube API key verification failed

### ISSUE THREAD

**Issue by Archiefkast** [natumbri/mopidy-youtube#148]
My error log shows the following errors:

jun 19 20:30:19 raspberrypi mopidy[27280]: ERROR    [YouTubeBackend-3] mopidy_youtube Failed to verify YouTube API key, disabling API
jun 19 20:30:19 raspberrypi mopidy[27280]: INFO     [YouTubeBackend-3] mopidy_youtube using bs4API

I created an API key for 'YouTube Data API v3' on https://console.developers.google.com/apis/

[youtube]
enabled = true
youtube_api_key = ***************************************
api_enabled = true
search_results = 30

The amount of stars in my configuration above represents the length of the API key which I copied from Google's API library.

I tried to delete the API key and create another one. I also tried to use another email address to create the API key. Both with no luck.

Do you have any suggestions?

Thanks in advance

**Comment by natumbri** [comment]
Strange. How would you feel about sending me an API key that you have created and that you have confirmed doesn't work. I could test it, and then you can cancel it.  

Honestly, I don't use an API key these days; I find it works just as well without one.

**Comment by Archiefkast** [comment]
Thank you for your quick response. I sent you an email with extra information including the full API key. Please let me know if this is sufficient for you to test.

**Comment by natumbri** [comment]
Hi @Archiefkast - thanks for the above and for your email. I have tested your API key; the error I get is:
```
2020-06-20 20:46:46,691 ERROR [16374:YouTubeBackend-6] mopidy_youtube: search error "{'code': 403, 'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'errors': [{'message': 'The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.', 'domain': 'youtube.quota', 'reason': 'quotaExceeded'}]}"
2020-06-20 20:46:46,693 ERROR [16374:YouTubeBackend-6] mopidy_youtube: Failed to verify YouTube API key, disabling API
```
I'm not sure what your quota is, or what you might use it for, or how much using mopidy-youtube uses it up, but it looks like it has been exceeded?  Maybe you can have a look at your usage in the google console?

**Comment by Archiefkast** [comment]
Thank you very much for your research!

The strange thing is, I see that there are a few requests on the API key that I generated yesterday. All these request results in an error:

![image](https://user-images.githubusercontent.com/30975633/85200408-60dd3f00-b2f7-11ea-9430-5fb4c1290e28.png)

In the quota section, the usage indicates 0. But the item 'Queries per day' has a limit of 0. Could that be the problem? Do you need a paid subscription to increase this limit? See the image below:

![image](https://user-images.githubusercontent.com/30975633/85200394-46a36100-b2f7-11ea-8377-bee2f99a7df2.png)

**Comment by natumbri** [comment]
The limit of 0 queries per day could be your problem.  My free account has a limit of 10000 per day, and mopidy-youtube does use them.  You can see the small number of queries I ran with my API key before I tried with your API key:
![image](https://user-images.githubusercontent.com/4251285/85200733-4fb72100-b33d-11ea-88ec-3bb2b645550f.png)
... you can also see that I basically never use my own API key; as I said, I've found using mopidy-youtube without the API key works just as well (and you don't have to worry about quotas).

**Comment by Archiefkast** [comment]
This should be the cause. I will look for more information about this 0 requests per day limit. I like the API connection because of the personal playlists.

This issue can be closed now, it looks like it has nothing to do with the plugin.

Thank you very much for your effort @natumbri !

**Comment by Archiefkast** [comment]
I deleted my project on https://console.developers.google.com/apis/ and created a new one. Then I created a new API key, entered it in my Mopidy configuration and restarted Mopidy. Now it is working! See the log below:

jun 20 14:13:57 raspberrypi mopidy[7249]: INFO     [YouTubeBackend-3] mopidy_youtube YouTube API key verified

Again, thank you very much @natumbri ! You made my day :)

**Comment by natumbri** [comment]
Glad it is working for you! Would you mind just explaining a bit how you use personal playlists? I'm interested to know how people actually use the plugin, especially if they are using it in a way different to how I use it.

**Comment by Archiefkast** [comment]
**My setup:**
- Mopidy with the YouTube plugin
- Icecast: a free, open source media streaming server (https://icecast.org/)
- Home Assistant: a free, open source home automation solution (https://www.home-assistant.io/)
- Google chromecast audio (in several rooms of my home)

**Streaming through Icecast**
I have configured the Mopidy audio output to stream through Icecast:
(https://docs.mopidy.com/en/release-2.2/audio/#streaming-through-icecast)

**Select a playlist in Home Assistant**
In Home Assistant I created a dropdown for selecting a playlist (that will automatically load a YouTube playlist in Mopidy):

![image](https://user-images.githubusercontent.com/30975633/85216986-a6e3e280-b38b-11ea-9f4a-cfd96e196065.png)

**Play the selected playlist in the desired room**
In Home Assistant I also created a dropdown for each room with a Google chromecast audio to select the Mopidy input:

![image](https://user-images.githubusercontent.com/30975633/85216975-7e5be880-b38b-11ea-9f03-f6bd7ac292e3.png)

**Shuffle**
I have to figure out how I can let Home Assistant shuffle Mopidy's playlist after loading a YouTube playlist. I saw in the Home Assistant documentation that there is an option to set the shuffle and it is compatible with MPD (https://www.home-assistant.io/integrations/media_player/).

![image](https://user-images.githubusercontent.com/30975633/85217419-07c1e980-b391-11ea-96a6-06a9d6c21f18.png)

**Delay in audio playback**
It will take several seconds for the Google chromecast audio to buffer the streaming. There is also a delay of multiple seconds in the audio playback when you stop or pause Mopidy. But I use this functionality to play multiple of my own selected tracks at dinner time or when I do my fitness workout. So this delay is not a problem for me. 

I know Spotify is probably an easier solution. But this one is free ;)

Please let me know if you have any further questions.

**Comment by natumbri** [comment]
Thanks for the detailed description.  I'm doing something similar, but with snapcast instead of icecast, and domoticz instead of home assistant.

I don't know how home assistant works, but if it can do this...
```
curl -d '{"jsonrpc": "2.0", "id": 1, "method": "core.tracklist.shuffle"}' -H 'Content-Type: application/json' http://localhost:6680/mopidy/rpc
```
... your playlist will be shuffled.

**Comment by Archiefkast** [comment]
You're welcome. 

A great advantage of Snapcast is that you are able to synchronize audio between multiple rooms. I will certainly try that solution later, when I have enough Pi's to run the client on :) 

Thank you for the suggestion regarding shuffle, I will try that one.

**Comment by natumbri** [comment]
Also, if you want random play mode, instead of shuffling the playlist, you could do this:
```
curl -d '{"jsonrpc": "2.0", "id": 1, "method": "core.tracklist.set_random", "params": {"value": true}}' -H 'Content-Type: application/json' http://localhost:6680/mopidy/rpc
```
One good thing about snapcast is the client runs on android (so you can use an old android phone as a receiver) and on openwrt, so you can use just about any device that is supported by openwrt and has a usb port as a client.  

I've done it with some success using a [TL-WR703N](https://openwrt.org/toh/tp-link/tl-wr703n) (which is a very, very basic router) with a very cheap CM108 usb sound card.  

I imagine you could do the same with icecast...

**Comment by Archiefkast** [comment]
That's really a good thing, it offers a way to reuse old devices. This is a nice one for my holiday :)

Thank you very much for your help and your suggestions!

**Comment by Archiefkast** [comment]
Random play mode works like a charm! :)
