### ISSUE TITLE
Youtube Music support

### ISSUE THREAD

**Issue by balsoft** [natumbri/mopidy-youtube#151]
I'm considering switching from Google Play Music (which appears to be living its last years) to Youtube Music. Thus, I would like to have a plugin that would allow me to listen to my collection via mopidy.

If supporting Youtube Music in this extension is too hard (as I understand, it has an API completely different from Youtube proper), do you think `mopidy-gmusic` would be a better place to ask?

**Comment by SuperSandro2000** [comment]
YouTube Music is just a different UI put on top of YouTube with very minimal changes.

**Comment by balsoft** [comment]
Ok, so the question then becomes is it possible to get my music library to show up in the virtual filesystem like it does with gmusic? Also, would it be possible to somehow search for "only music" on Youtube?

**Comment by natumbri** [comment]
It is an interesting idea.  Can any user  upload content to YouTube Music (like they can to YouTube)?  Or is it more like Spotify/Google Play Music/iTunes, where 'official' content is made available to users?  Or both? 

I assume that YouTube Music - like Google Play Music etc - supports concepts like 'Albums' and 'Artists' - things that are not really a part of YouTube.

**Comment by SuperSandro2000** [comment]
Just test it on https://music.youtube.com/. It is free.

> Can any user upload content to YouTube Music (like they can to YouTube)?

There is an option when you click your avatar. Didn't test it.

> Or is it more like Spotify/Google Play Music/iTunes, where 'official' content is made available to users?

It can definitely do that.

> I assume that YouTube Music - like Google Play Music etc - supports concepts like 'Albums' and 'Artists' - things that are not really a part of YouTube.

Albums are playlists which can be listened on youtube. Just remove ``music.`` in the url.

Artists are just YouTube Channel ~~with the special Artist symbol~~.

Edit: You can literally view your own channel in YouTube Music but it is missing a lot of the infos and special buttons.

**Comment by natumbri** [comment]
Way back when, possibly before mopidy went to python3, and definitely before I started 'officially' maintaining mopidy-youtube,  @DonnieWest had a crack at adding youtube-music to mopidy-youtube: https://github.com/DonnieWest/mopidy-youtube/tree/youtubeMusic

By popular demand - and for the purposes of experimentation - I've grafted the work @DonnieWest did onto the current develop branch of mopidy-youtube.  It has its own branch: https://github.com/natumbri/mopidy-youtube/tree/feature/youtube-music.

Would be interested to hear any thoughts anyone has about this...

**Comment by natumbri** [comment]
@sigma67 has also done some very interesting work on the youtube music api: https://github.com/sigma67/ytmusicapi

**Comment by natumbri** [comment]
Ok, I'm also trying out the excellent work by @sigma67.  I have created a [new branch](/natumbri/mopidy-youtube/tree/feature/ytmusicapi) with the progress so far.

**Comment by eeyun** [comment]
Very rad. Thanks for doing this - noticing in the branch I have to call search twice to get any results to come up, but then everything plays fine. Would be cool to have access to the dynamic playlists available!

**Comment by RossWilliamson** [comment]
Any hints on getting the youtube-music extension working?  I've cloned the gitrepo, checked out the feature/ytmusicapi branch, did  a python3 setup.py install.  I have my API key in the config file and it connects to youtube OK but no joy accessing anything youtube music related

**Comment by DIYglenn** [comment]
I get the annoyance with YouTube Music and YouTube sharing “Liked” songs and videos, it is two different platforms that IMHO shouldn’t share anything between each other. 
But as a cheap family subscription of YouTube Premium gives you access to both YouTube without ads and YouTube Music, it is a service that I think will increase in popularity. 

I definitely hope there is a way to support Premium subscriptions. I’ll help in any way I can.

**Comment by sprnza** [comment]
Hi there! Not pushing, just curious. Is there any chances to get this implemented?

**Comment by natumbri** [comment]
Hi @sprnza , @balsoft More Youtube Music support is on the way.  

Browsing your own playlists is now supported in the [yt-playlists branch](/natumbri/mopidy-youtube/tree/feature/yt-playlists).  There's no documentation yet, so have a look in #174 and #183 to see how it is supposed to work.

I'm going to close this issue, given the work that is being done on the `yt-playlists` branch.  If there are other youtube music specific features that make sense for mopidy-youtube, feel free to open an issue. Maybe dynamic playlists @eeyun ?
