### ISSUE TITLE
Mopidy-youtube configuration options meaning

### ISSUE THREAD

**Issue by eziosoma** [natumbri/mopidy-youtube#152]
Hello natumbri,
can you explain what each configuration options do? The only clear to me is search_results.

```
threads_max = 16
search_results = 15
playlist_max_videos = 20

```
If you want mopidy-youtube to autoplay related videos, set autoplay_enabled = true:

`autoplay_enabled = true`

If autoplay is enabled, other options are:

```
strict_autoplay = [true/false]
max_autoplay_length = [maximum length of track in seconds or None]
max_degrees_of_separation = [defaults to 3]
```

**Comment by natumbri** [comment]
Hi @eziosoma - you are quite right; the documentation really does need to provide a bit more explanation.  I'll try to get to that shortly!  

threads_max really sets how many parallel downloads of youtube happen at once.  

if autoplay is enabled, and a youtube track is played and is the last track in the playlist, it will add another, hopefully related, track to the playlist - so it will continuously play music.  The other options relate to how that works. 

As I said, I'll try to get the documentation right shortly, but hopefully that is enough to get you going for now.

**Comment by eziosoma** [comment]
Sorry @natumbri  I'm stil a little bit confused.

> threads_max really sets how many parallel downloads of youtube happen at once.

Parallel download of what? Do you mean that the videos of youtupe are downloaded in parallel?

> max_degrees_of_separation = [defaults to 3]

What are "degrees of separation"

**Comment by natumbri** [comment]
> Sorry @natumbri I'm stil a little bit confused.
> 
> > threads_max really sets how many parallel downloads of youtube happen at once.
> 
> Parallel download of what? Do you mean that the videos of youtupe are downloaded in parallel?
> 

The metadata for each video that is returned by a search needs to be retrieved separately, particularly the download link. These can be retrieved in separate threads, in parallel, in the background, so when it comes time to play the track, everything is ready.

> > max_degrees_of_separation = [defaults to 3]
> 
> What are "degrees of separation

This is for the autoplay function. It is a measure of how related the autoplayed tracks are to the original track that triggered autoplay. The higher the number, the further from the original the autoplayed goes.

**Comment by eziosoma** [comment]
Many thanks for the clarification Natumbri.
Regarding the degree of separation , is it a function provided by youtube?
I'm curious, how I can find more documentation regarding this subject?

**Comment by natumbri** [comment]
Have a look at #139 where @Mohawi introduced the feature, and in #141 where it is discussed a bit. 

There is a function in the YouTube API that returns related videos - you can check that out on Google's development website - it's pretty well documented. 

I've emulated that function for the people who don't enable the API, much in the same way that I've emulated the other API functions that are used.

Degrees of separation is not a YouTube feature, it is really just a function of how I've implemented the autoplayer. The best documentation, at this stage, is the code (frontend.py).

**Comment by rohieb** [comment]
That leads me to the question, what features do I get by enabling the API? Is it needed at all?

**Comment by natumbri** [comment]
@rohieb I don't use the API but the code using it was written before I got here, so why not keep it, hey?

When Google changes the way the YouTube site presents, the non-API version will stop working and maybe we'll all have to use the API. But, for now, the non-API versions work.

On the YouTube Music branch, the API version returns the number of tracks in an album much more quickly than the non-API version.
