### ISSUE TITLE
YouTube track keeps restarting at 3-4 seconds mark

### ISSUE THREAD

**Issue by youneverknow1** [natumbri/mopidy-youtube#154]
I installed Mopidy, Mopidy-YouTube extension and also configured YouTube API key.  I can search using Mopidy WebClient but when I select and play YouTube Track it starts and restarts at 4 seconds and keeps restarting.

**Comment by zerote000** [comment]
I'm experiencing the same issue, both with and without using the Youtube API key, trying to play from Youtube from the Iris web-ui.

Looking at the websockets, it seems like clicking on a track only triggers status updates, no request is sent to play the track.

**Comment by natumbri** [comment]
Could this be related to the problem described here: https://github.com/mopidy/mopidy/pull/1935

Perhaps someone could apply the patch to mopidy and report back on whether it fixes anything?

**Comment by natumbri** [comment]
Is this still a problem with the current version?

**Comment by natumbri** [comment]
I'll assume this is resolved.
