### ISSUE TITLE
Youtube can play music but not searching

### ISSUE THREAD

**Issue by shameerariff** [natumbri/mopidy-youtube#158]
The YouTube plugin can play songs from the previously saved YouTube playlist, but unable to search. I received the following log. 

Oct 24 23:16:42 SmartSpeaker mopidy[20210]: INFO     2020-10-24 23:16:42,096 [20210:YouTubeBackend-3] mopidy_youtube
Oct 24 23:16:42 SmartSpeaker mopidy[20210]:   Searching YouTube for query "top hits 2017"
Oct 24 23:16:42 SmartSpeaker mopidy[20210]: INFO     2020-10-24 23:16:42,097 [20210:YouTubeBackend-3] mopidy_youtube
Oct 24 23:16:42 SmartSpeaker mopidy[20210]:   session.get triggered: search
Oct 24 23:16:43 SmartSpeaker mopidy[20210]: INFO     2020-10-24 23:16:43,551 [20210:YouTubeBackend-3] mopidy_youtube
Oct 24 23:16:43 SmartSpeaker mopidy[20210]:   nothing in the soup, trying japi
Oct 24 23:16:43 SmartSpeaker mopidy[20210]: ERROR    2020-10-24 23:16:43,557 [20210:YouTubeBackend-3] mopidy_youtube
Oct 24 23:16:43 SmartSpeaker mopidy[20210]:   search error "'NoneType' object has no attribute 'group'"
Oct 24 23:16:43 SmartSpeaker mopidy[20210]: WARNING  2020-10-24 23:16:43,558 [20210:Core-15] mopidy.core.library
Oct 24 23:16:43 SmartSpeaker mopidy[20210]:   YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.

The youtube-dl and the remaining are up to date.

The following log shows it can play YouTube songs

Oct 24 23:35:09 SmartSpeaker mopidy[20210]:     raise value
Oct 24 23:35:09 SmartSpeaker mopidy[20210]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Oct 24 23:35:09 SmartSpeaker mopidy[20210]:     response = self._handle_receive(envelope.message)
Oct 24 23:35:09 SmartSpeaker mopidy[20210]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
Oct 24 23:35:09 SmartSpeaker mopidy[20210]:     return callee(*message.args, **message.kwargs)
Oct 24 23:35:09 SmartSpeaker mopidy[20210]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/backend.py", line 240, in lookup
Oct 24 23:35:09 SmartSpeaker mopidy[20210]:     name=video.title.get().replace(
Oct 24 23:35:09 SmartSpeaker mopidy[20210]: AttributeError: 'NoneType' object has no attribute 'replace'
Oct 24 23:35:18 SmartSpeaker mopidy[20210]: INFO     2020-10-24 23:35:18,695 [20210:YouTubeBackend-3] mopidy_youtube
Oct 24 23:35:18 SmartSpeaker mopidy[20210]:   youtube PlaybackProvider.translate_uri "youtube:video/Naanum Rowdy Dhaan - Thangamey Official Video Anirudh Vijay Sethupathi Vignesh Sh
ivan.4bZ-MAOLbGc"

**Comment by 2e0byo** [comment]
An upgrade to the development version of mopidy_youtube fixed this for me.  I.e. 
```
pip3 --remove mopidy_youtube
python3 -m pip install https://github.com/natumbri/mopidy-youtube/archive/develop.zip
```

The differences are in `/mopidy_youtube/apis/youtube_bd4api.py`, specifically (I think) b0e8128c1145985c2b09d793d9916c0ffc338c72 . So I suppose in general we just wait for the development version to be packaged up.

**Comment by shameerariff** [comment]
@2e0byo Wow it works. Thanks for the update. Will test it if and let you know if any issues, may help you in the development and bug fixes.

**Comment by pegelf** [comment]
Thank you for your notice, @2e0byo. Updating to the development version also worked for me.

I just wanted to add that "pip3 --remove" didn't work for me and if others want to try your solution they should use those commands:
```
python3 -m pip uninstall Mopidy-YouTube 
python3 -m pip install https://github.com/natumbri/mopidy-youtube/archive/develop.zip
```

**Comment by 2e0byo** [comment]
Bother, yes it’s `uninstall` not `remove`, thank you!
