### ISSUE TITLE
Allow to use youtube-dl alternatives

### ISSUE THREAD

**Issue by Dzordzu** [natumbri/mopidy-youtube#160]
Because of the #159 I suggest to move to [youtube-dlc](https://github.com/blackjack4494/yt-dlc/issues) (or simply allow to choose library).

**Comment by Dzordzu** [comment]
## Option 1
Just replace `youtube-dl` to `youtube-dlc`

## Option 2
IMHO a better option. More flexible and can prevent similar situations in the future.

Add a new dependency (youtube-dlc) and add possibility to dynamically load library (using for ex. a new config property). 
Then replace all imports youtube-dl imports by 
```
import importlib
importlib.import_module(YOUTUBE_DL_MODULE)
```

**Comment by Dzordzu** [comment]
It's just a suggestion. If @natumbri choose any of this options, I will prepare a PR with the solution

**Comment by Dzordzu** [comment]
Also we can consider [this repo](https://github.com/youtube-dl2/youtube-dl)

**Comment by savage93** [comment]
Since youtube-dlc seems to have more attention from developers, I'd also consider it as a replacement for youtube-dl, which also had problems with DMCA lately.

I had problems with playback while using youtube-dl ([this](https://github.com/blackjack4494/yt-dlc/issues/13)), but after installing youtube-dlc and simply changing the import in youtube.py from `import youtube_dl` to `import youtube_dlc as youtube_dl` the playback was fine, since the issue has already been resolved in the youtube_dlc codebase.

**Comment by djmattyg007** [comment]
Is this actually a concern now that youtube-dl's DMCA woes are over?

**Comment by natumbri** [comment]
My inclination is to continue to use youtube_dl, rather than the dlc fork. But I'm not against putting in a config option allowing for the selection of dlc, if that is preferred. And if in the future it becomes clear that youtube_dlc is a better default, we can make that change then.

If someone (@Dzordzu ?) wants to make a PR on that basis, go right ahead, with my thanks!

Cheers
Nik

**Comment by Dzordzu** [comment]
Currently I'm quite busy. But I will add this as my TODO later task

**Comment by l3d00m** [comment]
youtube-dlc seems like a bad choice now that the dust has settled, the last update it got was 2 months ago.

**Comment by Dzordzu** [comment]
As of now, I neither have time nor will to create dynamic loading for abandoned package. Closing (for a time?)

**Comment by natumbri** [comment]
Thanks anyway for the suggestion @Dzordzu - I think this could easily have been the right thing to do, if things had gone differently for YouTube-dl. But, in the circumstances, I think you are right to close. And you never know what may happen in the future - I suspect Google will not give up that easily, in the long run...

**Comment by Dzordzu** [comment]
Whis aged veeery bad. So as I promised, I've created code that allows dynamic library switching. It works on my setup

**Comment by Dzordzu** [comment]
> Closing (for a time?)

Also, damn me. Why I had to be right about it :(

**Comment by natumbri** [comment]
Thanks - I'll have a look. First impression is that it all seems a bit complicated? Why not just use something like `youtube.youtube_dl_library = config["youtube"]["youtube_dl_library"]`  (with a default of `youtube_dl`) in backend.py, then `youtube_dl = importlib.import_module(youtube_dl_library)` in youtube.py?

**Comment by Dzordzu** [comment]
I was thinking about that at first, but droped this idea. If you wish I can change it :3

**Comment by natumbri** [comment]
#211 added the option to set youtube_dl package by config option.

**Comment by Dzordzu** [comment]
Just want to say - thank you @natumbri :)

**Comment by natumbri** [comment]
Thanks to you, too @Dzordzu - appreciate the suggestion and ideas for how to implement.

**Comment by natumbri** [comment]
Thanks to you, too @Dzordzu - appreciate the suggestion and ideas for how to implement.

**Comment by Dzordzu** [comment]
Well, dependency is still present and it can provide issues during youtube-dl uninstallation process

**Comment by Dzordzu** [comment]
@natumbri IMHO, it (this dependecy) should be removed

**Comment by natumbri** [comment]
@Dzordzu - could you please point to where - youtube_dlc isn't a dependency, as far as I can tell...

**Comment by Dzordzu** [comment]
I mean youtube-dl dependency. Now it's getting out of hand during removal of the system package. Maybe we should consider removing it? And add list of possible packages in the readme?

**Comment by natumbri** [comment]
Oh right - you mean remove `youtube-dl` as a dependency. 

Do you think there has to be a default ytdl package? If so, whatever the default is should be a dependency, shouldn't it? 

Or are you saying have no default, and no dependency, and just tell people that they have to pick one and install it when they install mopidy-youtube, much in the same way people are told they need to separately install the gstreamer plugins.

**Comment by Dzordzu** [comment]
> Do you think there has to be a default ytdl package? If so, whatever the default is should be a dependency, shouldn't it?

As of now - no. There was no response from the developer and community is still during the process of migration to the yt-dlp.

> Or are you saying have no default, and no dependency, and just tell people that they have to pick one and install it when they install mopidy-youtube

Yep. We can try it **for a very few months**. Let's say to the release following the next one. It just needs to be quite high in the documentation and error handling of missing youtube-dl alternative (maybe with links to both of the packages) must be visible in the main logs. For this period, we can also nullify the default value for `youtube_dl_package` and make it (temporary) a required value. 

Doing a hack with installation from the code would be (IMHO) a bad idea.

But it's just my opinion. Maybe you and other memebers of this community should say what you think?

**Comment by djmattyg007** [comment]
I don't think it's realistic to expect these packages to remain compatible in all the ways we need going forward. Youtube-dl was always first and foremost a command-line utility. They will prioritise stability of the CLI experience (flags, arguments, etc), but I wouldn't expect them to preserve compatibility as a library forever-more.

Therefore I think it should be a priority in the medium term to select an implementation and run with it. `yt-dlp` definitely seems to be the focus of the community moving forward, so I think this project should follow along.

Having said all of the above, I don't expect the library interfaces to change drastically quickly. It should hopefully remain easy to pivot quickly again in future.
