### ISSUE TITLE
"my playlists" support

### ISSUE THREAD

**Issue by thanxx** [natumbri/mopidy-youtube#161]
Hi
Is there a way to browse the playlists of my youtube account? Is this on the roadmap?

**Comment by natumbri** [comment]
Hi @thanxx - mopidy-youtube can't log into your YouTube account at the moment, so I don't think so.  I don't really use playlists inside YouTube, so haven't been motivated to do it.  Maybe one day... or happy for someone else to do it and to merge it in.

**Comment by natumbri** [comment]
Hi!

Thanks heaps for the PR #174 - I'll have a closer look and maybe merge it in! Shouldn't be too hard to get it working without the api key. Not so sure about how it will go with the ytmusicapi, but it looks like a great start.

Thanks again,

Cheers
Nik

**Comment by natumbri** [comment]
@thanxx - I'm going to close this issue now; thanks to your contribution, it looks like we are well on the way.

**Comment by thanxx** [comment]
@natumbri thank you as well,
I am still planning to fix other things I mentioned in the #184
