### ISSUE TITLE
Please add support to set --cookies=<somepath> via config.

### ISSUE THREAD

**Issue by arnew** [natumbri/mopidy-youtube#162]
To access private playlists it may be very helpful to set --cookies via the mopidy config file (similar to the api-key).

**Comment by natumbri** [comment]
@arnew Are you able to explain further?

**Comment by arnew** [comment]
Sure! I have played around with mopidy-youtube integration and had great success using the API-Key, however I have problems accessing some material.

I would like to have the option of "being logged in" via the --cookies option of yt-dl to play around with and see if it solves my problems.

**Comment by codeasashu** [comment]
@arnew I am working on adding cookie support in youtube-music tracks. Please check the PR: #183

**Comment by natumbri** [comment]
@arnew I'm going to close this, on the basis that the [yt-playlists branch](/natumbri/mopidy-youtube/tree/feature/yt-playlists) (which will form the basis for the next release version) will solve this issue.

Feel free to re-open (and explain why) if you disagree.

Cheers,
Nik
