### ISSUE TITLE
Petition for a new release due to breaking changes

### ISSUE THREAD

**Issue by hexop** [natumbri/mopidy-youtube#163]
Hello,

I would like to request the addition of a new release, due to Youtube breaking changes as mentioned in #158

I'd love to install the development version of the package, but I'm not able to do it as I'm using NixOS (which means that I can't use pip). I've tried to override the version of the package, but I'm still new to the Nix language and I'm having trouble figuring out.

Thanks in advance

**Comment by natumbri** [comment]
Hi - sorry, I've been tied up with other things, but I'll try to get another release out shortly.

**Comment by natumbri** [comment]
mopidy-youtube 3.2 released - hopefully it fixes the problem.
