### ISSUE TITLE
Support URIs without video titles

### ISSUE THREAD

**Issue by djmattyg007** [natumbri/mopidy-youtube#165]
It would be nice to be able to enter `yt:video/jSJu8u3QOmk` as a URI and have it Just Work(tm).

It would also be nice to have URIs of the form `yt:video:jSJu8u3QOmk` to match the format used by the spotify extension.

I've taken a look at the codebase and I think it wouldn't be too difficult to implement. I'd be happy to work on a PR for this if you're interested. My one question should be whether or not the URIs actually returned with track data should be changed to use the new format?

**Comment by natumbri** [comment]
Sounds great - hack away! Maybe try for minimal change to start with, and see how it looks? I'm especially in favour of things that are consistent with other extensions (which I don't really know much about).

Cheers
Nik

**Comment by natumbri** [comment]
Merged it into a new branch, based on the latest develop.  Thanks!

Had some trouble with thumbnails; tried to hack something together - probably not idea.  If you have better ideas, go right ahead.

Have also been mucking around with threading and the YouTube Music API.  Changing lots of things around all at once  is not ideal for getting things working, but I don't think I've broken anything too badly.  I really do need to fix the threading properly... particularly as it relates to calling youtube_dl, to limit it to some number at a time.

**Comment by djmattyg007** [comment]
> Changing lots of things around all at once is not ideal for getting things working, but I don't think I've broken anything too badly

Modern development is all about moving fast and breaking things ;)

**Comment by natumbri** [comment]
merged into develop, with thanks to @djmattyg007
