### ISSUE TITLE
Some videos cause an error when added

### ISSUE THREAD

**Issue by bombpersons** [natumbri/mopidy-youtube#169]
It seems that some youtube videos just refuse to play because of an error in processing the video title? It sounds maybe related to [https://github.com/natumbri/mopidy-youtube/issues/165](https://github.com/natumbri/mopidy-youtube/issues/165)?

Here is a link to the video in question: https://www.youtube.com/watch?v=InwwkaoUBeg

Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:   youtube LibraryProvider.lookup "youtube:video/Dorian Electra - Sorry Bro (I Love You) (Official Video).InwwkaoUBeg"
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]: ERROR    2021-02-22 13:53:56,450 [147716:Core-8] mopidy.core.library
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:   YouTubeBackend backend caused an exception.
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]: Traceback (most recent call last):
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:   File "/usr/lib/python3.9/site-packages/mopidy/core/library.py", line 17, in _backend_error_handling
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:     yield
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:   File "/usr/lib/python3.9/site-packages/mopidy/core/library.py", line 217, in lookup
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:     result = future.get()
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:   File "/usr/lib/python3.9/site-packages/pykka/_threading.py", line 45, in get
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:     _compat.reraise(*self._data['exc_info'])
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:   File "/usr/lib/python3.9/site-packages/pykka/_compat/__init__.py", line 29, in reraise
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:     raise value
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:   File "/usr/lib/python3.9/site-packages/pykka/_actor.py", line 193, in _actor_loop
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:     response = self._handle_receive(envelope.message)
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:   File "/usr/lib/python3.9/site-packages/pykka/_actor.py", line 299, in _handle_receive
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:     return callee(*message.args, **message.kwargs)
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:   File "/usr/lib/python3.9/site-packages/mopidy_youtube/backend.py", line 240, in lookup
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]:     name=video.title.get().replace(
Feb 22 13:53:56 ARCHYSERVER mopidy[147716]: AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by djmattyg007** [comment]
It would be nice if a new release that includes #166 could be published.

**Comment by natumbri** [comment]
@djmattyg007 apologies I haven't published a new release with your work in it, I've been a little busy lately (new baby on 14/Feb), but will push out a new version shortly.  I appreciate your work!

**Comment by djmattyg007** [comment]
Congratulations! I hope all involved are healthy and doing well :)

**Comment by natumbri** [comment]
adding `yt:video:InwwkaoUBeg` works for me with the new version, so I'm closing this.  Thanks again @djmattyg007
