### ISSUE TITLE
No search results since today

### ISSUE THREAD

**Issue by PureTryOut** [natumbri/mopidy-youtube#170]
I've been using Youtube Mopidy quite happily for a few days, but since today it suddenly can't find results anymore.

The Mopidy log shows:

```
Apr 01 17:20:13 raspberrypi mopidy[27062]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'artist': ['Da Tweekaz']}"
Apr 01 17:20:13 raspberrypi mopidy[27062]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'album': ['Da Tweekaz']}"
Apr 01 17:20:13 raspberrypi mopidy[27062]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'any': ['Da Tweekaz']}"
Apr 01 17:20:13 raspberrypi mopidy[27062]: INFO     [YouTubeBackend-3] mopidy_youtube Searching YouTube for query "Da Tweekaz"
Apr 01 17:20:13 raspberrypi mopidy[27062]: INFO     [YouTubeBackend-3] mopidy_youtube session.get triggered: search
Apr 01 17:20:14 raspberrypi mopidy[27062]: INFO     [YouTubeBackend-3] mopidy_youtube nothing in the soup, trying japi
Apr 01 17:20:14 raspberrypi mopidy[27062]: ERROR    [YouTubeBackend-3] mopidy_youtube No data found on page
Apr 01 17:20:14 raspberrypi mopidy[27062]: ERROR    [YouTubeBackend-3] mopidy_youtube search error "No data found on page"
```

I guess something changed on Youtube that requires mopidy-youtube to make some changes? youtube-dl is the latest version, at the moment 2021.4.1, but I believe that is not relevant for just search results.

**Comment by gergely-lakos** [comment]
Same issue here.
```ápr 04 06:45:06 lz mopidy[62974]: INFO     2021-04-04 06:45:06,033 [62974:YouTubeBackend-3] mopidy_youtube      
ápr 04 06:45:06 lz mopidy[62974]:   youtube LibraryProvider.search "{'any': ['metallica']}"      
ápr 04 06:45:06 lz mopidy[62974]: INFO     2021-04-04 06:45:06,033 [62974:YouTubeBackend-3] mopidy_youtube
ápr 04 06:45:06 lz mopidy[62974]:   Searching YouTube for query "metallica"
ápr 04 06:45:06 lz mopidy[62974]: INFO     2021-04-04 06:45:06,033 [62974:YouTubeBackend-3] mopidy_youtube
ápr 04 06:45:06 lz mopidy[62974]:   session.get triggered: search
ápr 04 06:45:06 lz mopidy[62974]: INFO     2021-04-04 06:45:06,034 [62974:YouTubeBackend-3] mopidy_youtube
ápr 04 06:45:06 lz mopidy[62974]:   session.get triggered: bs4api run_search
ápr 04 06:45:06 lz mopidy[62974]: INFO     2021-04-04 06:45:06,725 [62974:YouTubeBackend-3] mopidy_youtube
ápr 04 06:45:06 lz mopidy[62974]:   nothing in the soup, trying japi
ápr 04 06:45:06 lz mopidy[62974]: ERROR    2021-04-04 06:45:06,726 [62974:YouTubeBackend-3] mopidy_youtube
ápr 04 06:45:06 lz mopidy[62974]:   No data found on page
ápr 04 06:45:06 lz mopidy[62974]: ERROR    2021-04-04 06:45:06,727 [62974:YouTubeBackend-3] mopidy_youtube
ápr 04 06:45:06 lz mopidy[62974]:   search error "No data found on page"
ápr 04 06:45:06 lz mopidy[62974]: WARNING  2021-04-04 06:45:06,728 [62974:Core-14] mopidy.core.library
ápr 04 06:45:06 lz mopidy[62974]:   YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.
```

Mopidy version: 3.1.1
Mopidy-YouTube version: 3.2

**Comment by gergely-lakos** [comment]
I debugged my error. The search is not working, because when backend want to search on youtube, first you got a page that google using cookies ("Before you continue to YouTube").
After you agreed this, redirected the search page. This is the reason why bs4api cannot find anything.

I solved this problem with creating Google api key, and enabled api in the mopidy.conf for youtube plugin.

**Comment by christian3107** [comment]
Good informations but i haven't api key, so i have updated "backend.py". Search for `"cookie"` and change value to `"PREF=hl=en; CONSENT=YES+cb.20210329-17-p0.fr+F+322;"`. I'have got consent value from my firefox session in developper mode or from extension [cookie.txt](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/). Now time to compile `python3 -m py_compile  /usr/local/lib/python3.7/dist-packages/mopidy_youtube/backend.py` for me. Reload and have fun with YT search

**Comment by PureTryOut** [comment]
I don't have a key either, and I don't want one either. Thanks for the tip @christian3107, but according to my Firefox developer tools the CONSENT cookie is set to "PENDING+870" which I guess isn't good enough. Strange, as I can watch videos in my browser just fine without any cookie popups.

**EDIT:** Actually, I got the cookie from incognito mode of my browser instead, there the correct value is set. This method works indeed, thanks! However, a more permanent solution will be needed.

**Comment by natumbri** [comment]
I'm not experiencing this issue, so hard for me to test.  

Query (for @christian3107 ): if the consent cookie is set to `CONSENT=YES;` without including `+cb.20210329-17-p0.fr+F+322` does it work?  I wouldn't be opposed to permanently setting `CONSENT=YES;` if that works for you, but I'd be reluctant to code the other stuff in - who knows what it means...?

**Comment by jonaspaulo** [comment]
Hi, same issue, it got past the no data found error after inputing the CONSENT with my specific cookie but then I get a new error:

May 09 18:08:27 livingroom mopidy[16285]: [youtube] azdwsXLmrHE: Downloading webpage
May 09 18:08:28 livingroom mopidy[16285]: ERROR    [ThreadPoolExecutor-2_0] mopidy_youtube audio_url error "'NoneType' object has no attribute 'get'"
May 09 18:08:28 livingroom mopidy[16285]: WARNING  [Core-7] mopidy.core.tracklist Track is not playable: youtube:video:azdwspxlmrhe

Any tips?

**Comment by christian3107** [comment]
Hi, minimale usable cookie for me is "PREF=hl=en; CONSENT=YES+20210329;" . Certainly you can set any valid date.
Searching for "azdwspxlmrhe" work fine on my device, with mopidy-youtube 3.2 and lastest youtube-dl version

**Comment by jonaspaulo** [comment]
Hi, just tried with your cookie and the same happens on any youtube url I try to play

**Comment by natumbri** [comment]
Not sure where to go with this; I'll include a minimal cookie in the next version, and we'll see what happens.  

In the meantime, the cookie is included in the [yt-playlists branch](/natumbri/mopidy-youtube/tree/feature/yt-playlists), which will form the basis for the next release version.
