### ISSUE TITLE
Remove 'nocheckcertificate' flag

### ISSUE THREAD

**Issue by djmattyg007** [natumbri/mopidy-youtube#175]
I noticed that `nocheckcertificate=True` is being passed to Youtube-DL:

https://github.com/natumbri/mopidy-youtube/blob/develop/mopidy_youtube/youtube.py#L292

Unless there's a very good reason to keep this, it would be ideal if it could be removed. If Youtube is compromised to the point where it's returning certificate errors, I'd rather not download anything from it than potentially download malicious content.

**Comment by natumbri** [comment]
I wonder why this was a Good Idea at the time it was inserted?

**Comment by djmattyg007** [comment]
Perhaps someone was following a poorly-written example from somewhere on the internet, or perhaps they were testing with a local server and forgot to remove some testing code. The fact is that if Youtube had SSL issues we'd have a lot more to worry about.

**Comment by natumbri** [comment]
This will happen in the next release.  It has already been implemented in the [yt-playlists branch](/natumbri/mopidy-youtube/tree/feature/yt-playlists), which will be the basis for the next release version.
