### ISSUE TITLE
Implement Youtube-DL "download in full" mode

### ISSUE THREAD

**Issue by djmattyg007** [natumbri/mopidy-youtube#176]
I would appreciate having the ability to make this extension just download tracks in full using Youtube-DL, and then play them directly off the local disk. Reasons:

- Youtube-DL is generally very fast to update when something is changed on Youtube's end, and I would prefer to depend on one parser, not two.
- I've found seeking on long (multi-hour) videos to be unreliable with the existing implementation. I just had to restart mopidy twice for it to recover from seeking half an hour forward in a 4 hour video.
- I suspect going forward we'll be playing a lot of these long ambience music style videos, and it would be good to not have to re-download them in full on a regular basis.

**Comment by natumbri** [comment]
I wonder if this is better done outside of mopidy-youtube?  
- use youtube-DL to download the track you want, 
- add it to the mopidy library, 
- play it using mopidy-file or mopidy-local?

**Comment by djmattyg007** [comment]
There's at least a couple of reasons why a roundabout solution may not be suitable:

1. Some users may not be technically savvy enough to perform all of those steps
2. As the person administering my household's multi-room audio system, I may not want to provide users with all of the access they'd need to perform those steps

I can guarantee you that if I told my wife she had to SSH into a server and run some commands just to play a music video from Youtube, she'd just do it some other way.

**Comment by natumbri** [comment]
Okay - @djmattyg007  that is a persuasive argument - my partner would also just do it a different way. (And would be none too happy that I had tried it on with a "why don't you just SSH into the server...').  So, in the interests of happy partners, and a slightly less clogged up internet, try this: [feature/cache](/natumbri/mopidy-youtube/tree/feature/cache)

Config option required:
```
allow_cache = true
```

Basically untested (someone really should write some tests, hey...); feedback appreciated.

**Comment by natumbri** [comment]
@djmattyg007 are you at all interested in having a look at this - no worries if not, but let me know and if you aren't, I'll close this issue.  

Cheers.

**Comment by djmattyg007** [comment]
I am, I just haven’t had a chance yet. I’m stuck in lockdown for at least another two weeks, so hopefully I’ll have time this weekend 👍

**Comment by natumbri** [comment]
Thanks @djmattyg007 - yeah, lockdown (now with curfew) sucks. Will be interested to hear if it works for you (and any ideas you might get have).

PS. I got bored and merged it into develop, so that's the one you need.

**Comment by djmattyg007** [comment]
Oh, are you in Melbourne too?

**Comment by natumbri** [comment]
Yep, sure am. WFH, home schooling, curfew, the whole box and dice.
