### ISSUE TITLE
Understand regular Youtube URLs

### ISSUE THREAD

**Issue by djmattyg007** [natumbri/mopidy-youtube#177]
What would be required to get Mopidy to understand regular Youtube URLs of the form `https://youtube.com/watch?v=somevideo`? As far as I've been able to tell it doesn't support them, but it's definitely possible I'm just holding it wrong.

**Comment by natumbri** [comment]
Adding an ordinary YouTube URL, prefixed by `yt:`, to your mopidy playlist should work: 

`[yt|youtube]:<url to youtube video>` 
`[yt|youtube]:<url to youtube playlist>` 

Works for me...
