### ISSUE TITLE
Make returning Youtube Playlists a toggle

### ISSUE THREAD

**Issue by Deep-Six** [natumbri/mopidy-youtube#178]
As  a user of youtube-music, I'd prefer that I have the ability to turn off Playlists and only list Albums  or Songs .

![scrn-clip-2021-04-20-22-17-46](https://user-images.githubusercontent.com/23326167/115500574-644a9b00-a226-11eb-882b-d0997aa5b7e2.png)

**Comment by natumbri** [comment]
Thanks @Deep-Six for the suggestion.  

When you say `As a user of youtube-music` do you mean that you have `musicapi_enabled = true` in your `mopidy.conf`?  Or do you mean that you are a user of youtube-music, more generally?

**Comment by Deep-Six** [comment]
The former, I have the music API = true.

**Comment by natumbri** [comment]
Thanks. Interesting - you should only be getting albums and songs.

**Comment by natumbri** [comment]
Currently it returns YouTube Music albums as mopidy albums and tracks.  I think it is enough to return them as albums.  #192 should make that change.
