### ISSUE TITLE
youtube is broken

### ISSUE THREAD

**Issue by mgrouch** [natumbri/mopidy-youtube#182]
Jun  1 03:01:43 lysmarine mopidy[613]: ERROR    [MainThread] mopidy.__main__ Extension youtube failed during setup. This might have left the registry in a bad state.
Jun  1 03:01:43 lysmarine mopidy[613]: Traceback (most recent call last):
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 159, in _new_conn
Jun  1 03:01:43 lysmarine mopidy[613]:     (self._dns_host, self.port), self.timeout, **extra_kw)
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 57, in create_connection
Jun  1 03:01:43 lysmarine mopidy[613]:     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/lib/python3.7/socket.py", line 748, in getaddrinfo
Jun  1 03:01:43 lysmarine mopidy[613]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Jun  1 03:01:43 lysmarine mopidy[613]: socket.gaierror: [Errno -2] Name or service not known
Jun  1 03:01:43 lysmarine mopidy[613]: During handling of the above exception, another exception occurred:
Jun  1 03:01:43 lysmarine mopidy[613]: Traceback (most recent call last):
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
Jun  1 03:01:43 lysmarine mopidy[613]:     chunked=chunked)
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
Jun  1 03:01:43 lysmarine mopidy[613]:     self._validate_conn(conn)
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 841, in _validate_conn
Jun  1 03:01:43 lysmarine mopidy[613]:     conn.connect()
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 301, in connect
Jun  1 03:01:43 lysmarine mopidy[613]:     conn = self._new_conn()
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 168, in _new_conn
Jun  1 03:01:43 lysmarine mopidy[613]:     self, "Failed to establish a new connection: %s" % e)
Jun  1 03:01:43 lysmarine mopidy[613]: urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0xb4581410>: Failed to establish a new connection: [Errno -2] Name or service not known
Jun  1 03:01:43 lysmarine mopidy[613]: During handling of the above exception, another exception occurred:
Jun  1 03:01:43 lysmarine mopidy[613]: Traceback (most recent call last):
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/local/lib/python3.7/dist-packages/requests/adapters.py", line 449, in send
Jun  1 03:01:43 lysmarine mopidy[613]:     timeout=timeout
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
Jun  1 03:01:43 lysmarine mopidy[613]:     _stacktrace=sys.exc_info()[2])
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 398, in increment
Jun  1 03:01:43 lysmarine mopidy[613]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Jun  1 03:01:43 lysmarine mopidy[613]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='music.youtube.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0xb4581410>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Jun  1 03:01:43 lysmarine mopidy[613]: During handling of the above exception, another exception occurred:
Jun  1 03:01:43 lysmarine mopidy[613]: Traceback (most recent call last):
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/lib/python3/dist-packages/mopidy/__main__.py", line 129, in main
Jun  1 03:01:43 lysmarine mopidy[613]:     extension.setup(registry)
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/__init__.py", line 35, in setup
Jun  1 03:01:43 lysmarine mopidy[613]:     from .backend import YouTubeBackend
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/backend.py", line 9, in <module>
Jun  1 03:01:43 lysmarine mopidy[613]:     from mopidy_youtube.apis import youtube_api, youtube_bs4api, youtube_music
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/apis/youtube_music.py", line 10, in <module>
Jun  1 03:01:43 lysmarine mopidy[613]:     ytmusic = YTMusic()
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/ytmusic.py", line 87, in __init__
Jun  1 03:01:43 lysmarine mopidy[613]:     self.headers.update(get_visitor_id(self._send_get_request))
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/helpers.py", line 75, in get_visitor_id
Jun  1 03:01:43 lysmarine mopidy[613]:     response = request_func(YTM_DOMAIN)
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/local/lib/python3.7/dist-packages/ytmusicapi/ytmusic.py", line 137, in _send_get_request
Jun  1 03:01:43 lysmarine mopidy[613]:     response = requests.get(url, params, headers=self.headers, proxies=self.proxies)
Jun  1 03:01:43 lysmarine mopidy[613]:   File "/usr/local/lib/python3.7/dist-packages/requests/api.py", line 76, in get

**Comment by natumbri** [comment]
I'm going to assume you got this working, and close the issue.  It doesn't look like a mopidy-youtube problem.  If it is still happening, feel free to reopen the issue, but you might need to do more than just post up a log file.
