### ISSUE TITLE
Youtube playlists

### ISSUE THREAD

**Issue by natumbri** [natumbri/mopidy-youtube#184]
A place for working on playlist support.

[Branch](/natumbri/mopidy-youtube/tree/feature/yt-playlists)

YouTube API - @thanxx
https://github.com/natumbri/mopidy-youtube/pull/174#issue-617461441

YouTube Music - @codeasashu
https://github.com/natumbri/mopidy-youtube/pull/183#issue-677413956

**Comment by natumbri** [comment]
Looks like there is a bit of work to do to get this working, without breaking existing functionality.
- [x] ytmusic without auth seems broken
- [ ] ytmusic albums vs ytmusic playlists; might have to turn albums into playlists and then pass both as mopidy playlists
- [x] YouTube API - move channel ID to config file
- [x]  problem with autoplay using YouTube API (may be unrelated)
- [x] remove duplicated `browse` method in `backend.py` introduced after the merge 
- [x] YouTube API - not all tracks loaded in a playlist (currently limited to 20), probably need to fix a request
- [x] YouTube API - channel name initialized as a channel owner name (i.e. my name) instead of original channel name (where the track belongs to)
- [ ] [to be continued]

Too bad there isn't a set of working unit tests...

**Comment by thanxx** [comment]
... moved to the upper comment

**Comment by codeasashu** [comment]
@natumbri Regarding the point `ytmusic without auth seems broken`, is there any open issue or steps to reproduce?

**Comment by natumbri** [comment]
Thanks @codeasashu for all the work you've been doing - this feature seems like a useful one.

I've been a bit busy on other things, so haven't put an issue etc, but when the auth cookie is blank, does the other functionality still work for you?  iI didn't for me - I got some kind of invalid cookie error when ytmusic is instantiated. (I've not really explored it further.)

**Comment by codeasashu** [comment]
@natumbri I've pushed a fix to address this (`ytmusic without auth seems broken`). It should fix the exception

**Comment by natumbri** [comment]
thanks @codeasashu - seems to be working now.  

I've tried to line up the YouTube API, the webscraping backend and the ytmusicapi backend so they all work in a similar way.  I think it is working.  The only real difference (that is intentional) at the moment seems to be that the ytmusicapi version shows you private playlists.  And maybe it is possible to browse other channels in the non-ytmusicapi versions?

**Comment by thanxx** [comment]
at the current state of `feature/yt-playlists` the playlist lookup doesn't return tracks/videos and even empty array on YoutubeAPI.
however, on newer branches it's fixed

**Comment by thanxx** [comment]
@natumbri could you please delete the following issue, as it turned out to be a default setting
```
 YouTube API - not all tracks loaded in a playlist (currently limited to 20), probably need to fix a request
```

**Comment by natumbri** [comment]
I merged this into [develop](/natumbri/mopidy-youtube/tree/develop), so I'm closing the issue.  Thanks everyone for the help.

Cheers.
