### ISSUE TITLE
mopidy-youtube not able to read metadata from youtube.

### ISSUE THREAD

**Issue by afredsa** [natumbri/mopidy-youtube#193]
Hello,

I have been using the youtube extension for a while; however, a month or more back it stopped doing searches and bringing back the metadata into existing playlists.   I can create a valid Mopidy URI and add it and it will play from YT.  And all existing URIs in playlists, still work but after a refresh of the playlists  ( in IRIS) the video info is all gone and the URIs are shown as seen like this:
```
youtube:video:-NuX79Ud8zI
- * YouTube Video:
```

Since I had a workaround I just kept using it; however, with the update to mopidy I decided to dig in a bit on this issue. I even tried to pull the GIT feature/yt_playlist tree but it did not help, and seemed to have no effect. 

### I run mopidy as a service on a pi4b arm64 rpios.
Everything is updated, (I will put all versions and system info at bottom). 
I do not use the API.  

### Error returned from trying to update track info
Below shows the error returned from systemctl when looking up metadata.  EG refresh a playlist that has a YT URI in it.  I believe it puts out one error block for every YT URI it tries to update.
```
sudo systemctl status mopidy
---snip---
Jul 09 22:09:21 elan4 mopidy[5486]: INFO     [ThreadPoolExecutor-32_0] mopidy_youtube session.get triggered: list_videos (experimental)
Jul 09 22:09:21 elan4 mopidy[5486]: INFO     [ThreadPoolExecutor-32_0] mopidy_youtube session.get triggered: bs4api run_search
Jul 09 22:09:23 elan4 mopidy[5486]: INFO     [ThreadPoolExecutor-32_0] mopidy_youtube nothing in the soup, trying japi
Jul 09 22:09:23 elan4 mopidy[5486]: ERROR    [ThreadPoolExecutor-32_0] mopidy_youtube list_videos error "Extra data: line 1 column 84575 (char 84574)"
Jul 09 22:09:23 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.lookup "youtube:video:-NuX79Ud8zI"
Jul 09 22:09:23 elan4 mopidy[5486]: [youtube] cBdNsC0BMT8: Downloading player 51ff6aac
```

### Error Returned from using search
When using the search feature from the front end only searching Youtube.  Nothing is returned. (eg search for big iron seen below).  The page will show a message saying "Searching Youtube XYZ" where XYZ is at least Tracks and Playlist and the rest is too fast to see.  

 I have tried many searches using only letters (no spaces, numbers or special chars) I have tried URL's and Video ID as well. all return nothing with the same type of error seen below (I think the "column X (char X-1)" changes).
The systemctl status shows after search:
```
Jul 09 22:09:23 elan4 mopidy[5486]: [youtube] cBdNsC0BMT8: Downloading player 51ff6aac
Jul 09 22:24:46 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'artist': ['Big Iron']}"
Jul 09 22:24:46 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'album': ['Big Iron']}"
Jul 09 22:24:46 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'any': ['Big Iron']}"
Jul 09 22:24:46 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube Searching YouTube for query "Big Iron"
Jul 09 22:24:46 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube session.get triggered: search
Jul 09 22:24:46 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube session.get triggered: bs4api run_search
Jul 09 22:24:47 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube nothing in the soup, trying japi
Jul 09 22:24:47 elan4 mopidy[5486]: ERROR    [YouTubeBackend-3] mopidy_youtube search error "Extra data: line 1 column 259817 (char 259816)"
Jul 09 22:24:47 elan4 mopidy[5486]: WARNING  [Core-11] mopidy.core.library YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.

Search for the video ID.

Jul 09 22:24:47 elan4 mopidy[5486]: WARNING  [Core-11] mopidy.core.library YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.
Jul 09 22:36:03 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'artist': ['-NuX79Ud8zI']}"
Jul 09 22:36:03 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'album': ['-NuX79Ud8zI']}"
Jul 09 22:36:04 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'any': ['-NuX79Ud8zI']}"
Jul 09 22:36:04 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube Searching YouTube for query "-NuX79Ud8zI"
Jul 09 22:36:04 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube session.get triggered: search
Jul 09 22:36:04 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube session.get triggered: bs4api run_search
Jul 09 22:36:04 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube nothing in the soup, trying japi
Jul 09 22:36:04 elan4 mopidy[5486]: ERROR    [YouTubeBackend-3] mopidy_youtube search error "Extra data: line 1 column 23126 (char 23125)"
Jul 09 22:36:04 elan4 mopidy[5486]: WARNING  [Core-11] mopidy.core.library YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.

Search for just the letter a
Jul 09 22:55:57 elan4 mopidy[5486]: WARNING  [Core-11] mopidy.core.library YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.
Jul 09 23:22:32 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'artist': ['a']}"
Jul 09 23:22:32 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'album': ['a']}"
Jul 09 23:22:32 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'any': ['a']}"
Jul 09 23:22:32 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube Searching YouTube for query "a"
Jul 09 23:22:32 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube session.get triggered: search
Jul 09 23:22:32 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube session.get triggered: bs4api run_search
Jul 09 23:22:33 elan4 mopidy[5486]: INFO     [YouTubeBackend-3] mopidy_youtube nothing in the soup, trying japi
Jul 09 23:22:33 elan4 mopidy[5486]: ERROR    [YouTubeBackend-3] mopidy_youtube search error "Extra data: line 1 column 230792 (char 230791)"
Jul 09 23:22:33 elan4 mopidy[5486]: WARNING  [Core-11] mopidy.core.library YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.
```

### Using feature/yt_playlist
I read some of the closed issues, where it was stated that using the GIT feature/yt_playlist tree may help with search issues.   This seemed to rev ytmusicapi from .15 to .18, but had no effect (tests above shown after proc below but are the same as before and I do not use the API).  

I am not quite sure if I did it right.  To use the tree I had to use sudo as mopidy is running as a service.
```
$ sudo python3 -m pip install git+git://github.com/natumbri/mopidy-youtube.git@feature/yt-playlists
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+git://github.com/natumbri/mopidy-youtube.git@feature/yt-playlists
  Cloning git://github.com/natumbri/mopidy-youtube.git (to revision feature/yt-playlists) to /tmp/pip-req-build-e0q7e8re
  Running command git clone -q git://github.com/natumbri/mopidy-youtube.git /tmp/pip-req-build-e0q7e8re
  Running command git checkout -b feature/yt-playlists --track origin/feature/yt-playlists
  Switched to a new branch 'feature/yt-playlists'
  Branch 'feature/yt-playlists' set up to track remote branch 'feature/yt-playlists' from 'origin'.
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done

---snip all requirements met and download of ytmusicapi---

Installing collected packages: ytmusicapi
  Attempting uninstall: ytmusicapi
    Found existing installation: ytmusicapi 0.15.1
    Uninstalling ytmusicapi-0.15.1:
      Successfully uninstalled ytmusicapi-0.15.1
Successfully installed ytmusicapi-0.18.0
```

### System Versions and settings:

```
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf deps" as user mopidy
Executable: /usr/bin/mopidy
Platform: Linux-5.10.46-v8+-aarch64-with-debian-10.10
Python: CPython 3.7.3 from /usr/lib/python3.7
Mopidy: 3.2.0 from /usr/lib/python3/dist-packages
---snip---
Mopidy-YouTube: 3.3 from /usr/local/lib/python3.7/dist-packages
  youtube-dl: 2021.2.10 from /usr/local/lib/python3.7/dist-packages
  cachetools: 4.2.1 from /usr/local/lib/python3.7/dist-packages
  Mopidy: 3.2.0 from /usr/lib/python3/dist-packages
  Pykka: 2.0.3 from /usr/lib/python3/dist-packages
  ytmusicapi: 0.18.0 from /usr/local/lib/python3.7/dist-packages
    requests: 2.25.1 from /usr/local/lib/python3.7/dist-packages
      certifi: 2018.8.24 from /usr/lib/python3/dist-packages
      chardet: 3.0.4 from /usr/lib/python3/dist-packages
      idna: 2.6 from /usr/lib/python3/dist-packages
      urllib3: 1.24.1 from /usr/lib/python3/dist-packages
  setuptools: 54.2.0 from /usr/local/lib/python3.7/dist-packages
  beautifulsoup4: 4.7.1 from /usr/lib/python3/dist-packages
  requests: 2.25.1 from /usr/local/lib/python3.7/dist-packages
    certifi: 2018.8.24 from /usr/lib/python3/dist-packages
    chardet: 3.0.4 from /usr/lib/python3/dist-packages
    idna: 2.6 from /usr/lib/python3/dist-packages
    urllib3: 1.24.1 from /usr/lib/python3/dist-packages
---snip---
GStreamer: 1.14.4.0 from /usr/lib/python3/dist-packages/gi
  Detailed information: 
    Python wrapper: python-gi 3.30.4
    Relevant elements:
      Found:
        uridecodebin
        souphttpsrc
        appsrc
        alsasink
        osssink
        oss4sink
        pulsesink
        id3demux
        id3v2mux
        lamemp3enc
        mpegaudioparse
        mpg123audiodec
        vorbisdec
        vorbisenc
        vorbisparse
        oggdemux
        oggmux
        oggparse
        flacdec
        flacparse
        shout2send
      Not found:
        flump3dec
        mad
```

Thank you for any help and for creating a really useful extension.

Side note:  my workaround was to search on youtube and copy the video ID out of the URL.   Bandcamp extension has a javascript link that scrapes and creates a Mopidy URI from pages... Something like that for YT would be cool  and probably easier because you could use the URL to get the Video ID directly.

**Comment by djmattyg007** [comment]
In theory there's already a fix for this problem in #170. Unfortunately the fix has not yet found its way into a release.

**Comment by afredsa** [comment]
> In theory there's already a fix for this problem in #170. Unfortunately the fix has not yet found its way into a release.

That is the reference I was referring to when I updated to the feature/yt_playlist tre, where @natumbri stated he updated that branch with the work around...  I upgraded to that branch and it had not effect.   It may have done more but it updated the ytmusicapi that I do not use.     

I am a bit of a  git noob, could someone point me to how to add the fix/patch.  (Should I downrev to the release, then apply what to get the fix?  Other than the feature tree I did not see where a fix was implemented in that issue.)

**Comment by afredsa** [comment]
There was some new error info in journalctl when executing:

```
Jul 27 14:44:59 elan4 mopidy[3379]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.lookup "youtube:video:06ht9MyJLT4"
Jul 27 14:44:59 elan4 mopidy[3379]: INFO     [ThreadPoolExecutor-2_0] mopidy_youtube session.get triggered: list_videos (experimental)
Jul 27 14:44:59 elan4 mopidy[3379]: INFO     [ThreadPoolExecutor-2_0] mopidy_youtube session.get triggered: bs4api run_search
Jul 27 14:45:01 elan4 mopidy[3379]: INFO     [ThreadPoolExecutor-2_0] mopidy_youtube nothing in the soup, trying japi
Jul 27 14:45:01 elan4 mopidy[3379]: ERROR    [ThreadPoolExecutor-2_0] mopidy_youtube list_videos error "Extra data: line 1 column 175110 (char 175109)"
Jul 27 14:45:01 elan4 mopidy[3379]: INFO     [YouTubeBackend-3] mopidy_youtube youtube PlaybackProvider.translate_uri "youtube:video:06ht9MyJLT4"
Jul 27 14:45:01 elan4 mopidy[3379]: [youtube] 06ht9MyJLT4: Downloading webpage
Jul 27 14:45:02 elan4 mopidy[3379]: [youtube] 06ht9MyJLT4: Downloading player 02486e7d
Jul 27 14:45:04 elan4 mopidy[3379]: ERROR    [Core-11] mopidy.listener Triggering event failed: stream_changed(uri)
Jul 27 14:45:04 elan4 mopidy[3379]: Traceback (most recent call last):
Jul 27 14:45:04 elan4 mopidy[3379]:   File "/usr/lib/python3/dist-packages/mopidy/listener.py", line 44, in on_event
Jul 27 14:45:04 elan4 mopidy[3379]:     getattr(self, event)(**kwargs)
Jul 27 14:45:04 elan4 mopidy[3379]:   File "/usr/lib/python3/dist-packages/mopidy/core/actor.py", line 85, in stream_changed
Jul 27 14:45:04 elan4 mopidy[3379]:     self.playback._on_stream_changed(uri)
Jul 27 14:45:04 elan4 mopidy[3379]:   File "/usr/lib/python3/dist-packages/mopidy/core/playback.py", line 147, in _on_stream_changed
Jul 27 14:45:04 elan4 mopidy[3379]:     self._trigger_track_playback_started()
Jul 27 14:45:04 elan4 mopidy[3379]:   File "/usr/lib/python3/dist-packages/mopidy/core/playback.py", line 514, in _trigger_track_playback_started
Jul 27 14:45:04 elan4 mopidy[3379]:     self.core.history._add_track(tl_track.track)
Jul 27 14:45:04 elan4 mopidy[3379]:   File "/usr/lib/python3/dist-packages/mopidy/core/history.py", line 31, in _add_track
Jul 27 14:45:04 elan4 mopidy[3379]:     ", ".join(artist.name for artist in track.artists)
Jul 27 14:45:04 elan4 mopidy[3379]: TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by natumbri** [comment]
Weird.  Thanks @afredsa.  I didn't have any trouble adding and playing `youtube:video:06ht9MyJLT4`.  I haven't seen this before: `ERROR    [ThreadPoolExecutor-2_0] mopidy_youtube list_videos error "Extra data: line 1 column 175110 (char 175109)"` and I'm not sure how to trigger it, which makes debugging your problem quite tricky...

Are you sufficiently confident to find and edit the python sources on your machine?  The change that was supposed to fix the `CONSENT` cookie issue (#170) is pretty basic, especially if you're not using the `ytmusicapi`.  No guarantees that it will help you tho...

**Comment by natumbri** [comment]
@afredsa try the new [fix/thumbnails](/natumbri/mopidy-youtube/tree/fix/thumbnails).

While I was trying to fix the thumbnail support, I started to get an error a bit like yours. Turns out the format of the data YouTube was sending changed unexpectedly. I fixed it - maybe it will solve your problem?

**Comment by natumbri** [comment]
@afredsa are you interested in testing this?  I've merged everything into [develop](/natumbri/mopidy-youtube/tree/develop).  No problem if you don't want to test - but let me know and I'll close off the issue.

**Comment by afredsa** [comment]
@natumbri, thank you.  I am away and have limited time right now, however,  I have tried both the things above your latest check but they did not seem to work... exactly.  

Setting the cookie seemed to change getting metadata in IRIS FE(front end) to be seen on "Now Playing" but only intermittently????. There was no change to the search which is returning no results or to the playlist metadata load.   The cookie behavior led me to think that search was being called/handled differently between search (which is currently returning nothing) and the metadata retrieval  (still getting no results)after cookie change.   At this point I started to use mscode to dig into functions being called (unfortunately I do not know how to debug mopidy as service on python, yet)  and I bogged down in printing debug INFO lines "Here"...  and bogged down in checking that it is not an FE problem: all 3 of the http FE (IRIS, Muse, Musicbox) have the same behavior and errors Seen in "Errors Returned from Search" in first post). I could not figure out how to limit ncmpc*(pp) mpd clients to a YT ext search only.  ncmpc did not return any YT hits and only output these lines below in journalctl before hitting an error in backend.radionet and resetting the mpd connection.  (All http clients are limited only to youtube search for testing, so the below error I do not think is germane to YT ext ).

```
Aug 17 03:15:40 elan4 mopidy[29066]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'track_name': ['Jude']}"
Aug 17 03:15:40 elan4 mopidy[29066]: ERROR    [MpdSession-22] pykka Unhandled exception in MpdSession (urn:uuid:---x---):
Aug 17 03:15:40 elan4 mopidy[29066]: Traceback (most recent call last):
Aug 17 03:15:40 elan4 mopidy[29066]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
Aug 17 03:15:40 elan4 mopidy[29066]:     response = self._handle_receive(envelope.message)
---snip---
Aug 17 03:15:40 elan4 mopidy[29066]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
Aug 17 03:15:40 elan4 mopidy[29066]:     return callee(*message.args, **message.kwargs)
Aug 17 03:15:40 elan4 mopidy[29066]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_radionet/library.py", line 91, in search
Aug 17 03:15:40 elan4 mopidy[29066]:     self.backend.radionet.do_search(' '.join(query['any']))
Aug 17 03:15:40 elan4 mopidy[29066]: KeyError: 'any'
Aug 17 03:15:41 elan4 mopidy[29066]: INFO     [MpdSession-23] mopidy_mpd.session New MPD connection from [---x---

```

The fix/thumbnails:   I tried:
sudo python3 -m pip install git+git://github.com/natumbri/mopidy-youtube.git@fix/thumbnails
This did not seem to install anything returning dependency met on all items.   So I am not sure anything was changed.   And had no change when testing after.  

I should be able to do:
sudo python3 -m pip install git+git://github.com/natumbri/mopidy-youtube.git@develop
In the next day or two...  If someone could tell me if this is the right way of updating (or should (and how do I) uninstall/reinstall) the YT Ext.  That could help me from wondering if what I am installing from git is changing anything.
....

I just did it...  No change after reboot.   
I checked /usr/local/lib/python3.7/dist-packages/mopidy_youtube/backend.py 
and it seemed to still have my cookie edit ("Cookie": "PREF=hl=en; CONSENT=YES+20210629;",) and my debug statements, and edit date, so I am not sure if the install works this way.  
```
pi@x:~ $ sudo python3 -m pip install git+git://github.com/natumbri/mopidy-youtube.git@develop
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+git://github.com/natumbri/mopidy-youtube.git@develop
  Cloning git://github.com/natumbri/mopidy-youtube.git (to revision develop) to /tmp/pip-req-build-72qvpqzc
  Running command git clone -q git://github.com/natumbri/mopidy-youtube.git /tmp/pip-req-build-72qvpqzc
  Resolved git://github.com/natumbri/mopidy-youtube.git to commit a3e44b2542d386a395795e191ac122adf3355398
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.3) (54.2.0)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.3) (2.25.1)
Requirement already satisfied: youtube-dl>=2020.12.22 in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.3) (2021.2.10)
Requirement already satisfied: Pykka>=2.0.1 in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.3) (2.0.3)
Requirement already satisfied: cachetools in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.3) (4.2.1)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.3) (4.7.1)
Requirement already satisfied: Mopidy>=3.1 in /usr/lib/python3/dist-packages (from Mopidy-YouTube==3.3) (3.2.0)
Requirement already satisfied: ytmusicapi>=0.17 in /usr/local/lib/python3.7/dist-packages (from Mopidy-YouTube==3.3) (0.18.0)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests->Mopidy-YouTube==3.3) (2.6)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3/dist-packages (from requests->Mopidy-YouTube==3.3) (3.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->Mopidy-YouTube==3.3) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->Mopidy-YouTube==3.3) (2018.8.24)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
pi@elan4:~ $ 

---Search output ---
Aug 17 03:40:54 elan4 mopidy[3800]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'artist': ['Running']}"
Aug 17 03:40:54 elan4 mopidy[3800]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'album': ['Running']}"
Aug 17 03:40:54 elan4 mopidy[3800]: INFO     [YouTubeBackend-3] mopidy_youtube youtube LibraryProvider.search "{'any': ['Running']}"
Aug 17 03:40:54 elan4 mopidy[3800]: INFO     [YouTubeBackend-3] mopidy_youtube Searching YouTube for query "Running"
Aug 17 03:40:54 elan4 mopidy[3800]: INFO     [YouTubeBackend-3] mopidy_youtube session.get triggered: search
Aug 17 03:40:54 elan4 mopidy[3800]: INFO     [YouTubeBackend-3] mopidy_youtube session.get triggered: bs4api run_search
Aug 17 03:40:55 elan4 mopidy[3800]: INFO     [YouTubeBackend-3] mopidy_youtube nothing in the soup, trying japi
Aug 17 03:40:55 elan4 mopidy[3800]: ERROR    [YouTubeBackend-3] mopidy_youtube youtube.py search error "Extra data: line 1 column 359951 (char 359950)"
Aug 17 03:40:55 elan4 mopidy[3800]: WARNING  [Core-11] mopidy.core.library YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.

```
I will try some things later.

**Comment by kingosticks** [comment]
Could it be that this [regex ](https://github.com/natumbri/mopidy-youtube/blob/develop/mopidy_youtube/apis/youtube_bs4api.py#L27) is greedy and is matching more than just the json structure you want, which then fails when you try and parse it? Try changing it to:
```
r"ytInitialData = ({.*?});",
```
Or add some debugging around there and see what you are actually matching.

**Comment by natumbri** [comment]
Thanks @kingosticks - I don't reckon that's the problem, but fixing that regex up is a good idea in any case. I'll look into it. (It _might_ be the problem, but I have a feeling it is something else.)

I'm going to simplify things shortly, by getting rid of the regex and bs4 based APIs and keeping only the official API, the JSON based one and YouTube Music. Hopefully fewer of these types of issues to sort out!

**Comment by kingosticks** [comment]
I saw a related issue for some other project where their regex was catching a load of random javascript that had suddenly appeared after the json struct they wanted and of course the json decoder complains about that. Worth a try!

**Comment by natumbri** [comment]
For sure.

But also, the version of the code you linked to, but which @afredsa appears _not_ to be using (despite his efforts), no longer uses the regex for searches. It is still used for other things, just not `search`. Instead of a `session.get` to a browser endpoint (which returns a webpage, complete with HTML, JavaScript and JSON, burried somewhere), `search` now uses a `session.post` to the `youtubei/v1` API endpoint (which returns pure JSON and so doesn't need a regex).

For the methods that do use the browser endpoint and regex, I think a bunch of JavaScript _has_ started appearing from time to time after the JSON I'm looking for, exactly as you have suggested. I haven't had time to look properly - instead I just caught the exception and 'fixed' it with an [ugly hack](https://github.com/natumbri/mopidy-youtube/blob/a3e44b2542d386a395795e191ac122adf3355398/mopidy_youtube/apis/youtube_bs4api.py#L147). I think your suggestion might be the correct way to fix it.

**Comment by afredsa** [comment]
Hello,

I uninstalled mopidy_youtube and then installed develop branch.   

All searchers are now working!  Thank you.

```
sudo systemctl stop mopidy
sudo  python3 -m pip uninstall Mopidy-YouTube
sudo python3 -m pip install git+git://github.com/natumbri/mopidy-youtube.git@develop
sudo systemctl start mopidy
```
Since you are working with KOS I am not sure if I should close.  Feel free to close, OR/and if you like I can do more testing, send logs, etc. (like if a new regex is created).  Thank you again.

**Comment by natumbri** [comment]
Great - I think this can be closed; I will take up @kingosticks useful suggestion, but no need to keep this issue open, I think.

Thanks @afredsa for your patience and for going through the testing and providing feedback. I'm glad to hear it's working for you.
