### ISSUE TITLE
No titles or previews

### ISSUE THREAD

**Issue by LeafyLappa** [natumbri/mopidy-youtube#202]
Hi!

On my mopidy instance the extension seems unable to fetch or parse titles and thumbnails.

<img src="https://user-images.githubusercontent.com/31704619/130740723-b2dd073d-da3b-426c-becf-ba6569d540c2.png" width="70%" height="70%">

(here using iris, same issue with moped)

This makes organizing videos pretty much impossible. Audio does play as expected. Is this a misconfiguration on my behalf, a bug or an API restriction? I'm not using API key or Music API.

**Comment by LeafyLappa** [comment]
On second thought using video id as track title seems intentional, but is it possible to see the title of a video anyhow?

**Comment by LeafyLappa** [comment]
Going through the source code of this extension I found that my track titles are in fact empty. At the same time making a manual API call with the same params as done programmatically yields a correct response:

```
{
  "items": [
    {
      "id": "5qap5aO4i9A",
      "snippet": {
        "title": "lofi hip hop radio - beats to relax/study to",
        "channelTitle": "Lofi Girl"
      },
      "contentDetails": {
        "duration": "P0D"
      }
    }
  ]
}
```

I'm not great at python so with all the concurrency in this project I'm not yet sure how to debug it to see what goes wrong.

**Comment by natumbri** [comment]
Hi @LeafyLappa - thanks for taking the time to try the extension and provide feedback. I just installed Iris today, to have a look for myself and it seems to be working just fine - I get titles and thumbnails.

Could you try with YouTube Music enabled? You don't need to get an API key or cookie, just set the relevant option to `True` in your config.

**Comment by LeafyLappa** [comment]
Does not seem to make a difference:

<img src="https://user-images.githubusercontent.com/31704619/131085291-81f66c5c-018b-483a-8fe6-3c9d336f5d14.png" width="70%" height="70%">

[Video](https://music.youtube.com/watch?v=WNeLUngb-Xg) that I tried adding.
I'm using mopidy 3.1.1, mopidy-youtube 3.3, youtube-dl 2021.6.6 from pip.
I also tried creating and using an API key, to no avail.

mopidy.conf:
```ini
[youtube]
; youtube_api_key = *my api key*
; api_enabled = true
musicapi_enabled = true
autoplay_enabled = true
max_autoplay_length = 21600
```

**Comment by LeafyLappa** [comment]
I just tried adding another [video](https://www.youtube.com/watch?v=kJQP7kiw5Fk) and I got both its title and thumbail:
<img src="https://user-images.githubusercontent.com/31704619/131086034-e1d2164e-cbae-43d3-8999-c6075e1802b2.png" width="70%" height="70%">
It seems adding videos or playlists via search works as it should but adding anything directly (via `iris/queue/add-uri` endpoint) does not. Search also won't work unless I set `musicapi_enabled` to true. Only videos available via Music API seem to be listed.

**Comment by natumbri** [comment]
Thanks. Weird; it seems to work for me, including with the Video that you tried adding [here](https://github.com/natumbri/mopidy-youtube/issues/202#issuecomment-906971021).

Any chance you'd be interested in trying out the [pre-release next version of the extension](https://github.com/natumbri/mopidy-youtube/tree/fix/deprecate-bs4api)?  It gets rid of a bunch of stuff that is of no or only marginal value, and tidies up what is left.  It might fix your problems... I'm not sure the correct way to install versions from git, but on linux something like this should do it:
```
python3 -m pip install https://github.com/natumbri/mopidy-youtube/archive/fix/deprecate-bs4api.zip
```

Depending on how you're set up, you may need to do that as a superuser (`sudo ...`)

cheers,
nik

**Comment by LeafyLappa** [comment]
Thank you, I tried reinstalling the extension with the link you gave and now everything works! I did exactly nothing else.

<img src="https://user-images.githubusercontent.com/31704619/131696227-f141c867-6e8f-4bc9-a440-bc4a5154dcca.png" width="70%" height="70%">

Even playback history works now, and it didn't before. In fact, the extension is now even able to play videos unavailable in my country, albeit title and thumbnail are missing as before (as I imagine they can't be fetched from the public API in such scenario).

Question: will I be able to upgrade to a newer version once it's on pypi?

**Comment by natumbri** [comment]
@LeafyLappa - not sure... I've just pushed a new version; give it a try

**Comment by LeafyLappa** [comment]
Everything seems to work, I'm closing this issue. Thank you!

**Comment by natumbri** [comment]
Good to hear! Thanks for the feedback
