### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by wrkzk** [natumbri/mopidy-youtube#204]
Every time I try to search for a track, I get this error: `YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.`

**Comment by natumbri** [comment]
thanks @wrkzk - try the latest version

**Comment by wrkzk** [comment]
I am not sure if this is particularly relevant to this issue, but I am running NixOS, and when I try to override the source to pull directly from the latest version of this repository like you suggested, I get this error:

`Could not find a version that satisfies the requirement ytmusicapi>=0.19 (from mopidy-youtube) (from versions: none)`

**Comment by natumbri** [comment]
Hmmmm... Are you able to install the current versions of `mopidy-youtube` and `ytmusicapi` from PyPI?  I'm not sure how NixOS works, but on other systems something like 
```
python3 -m pip install -U mopidy-youtube
```
should do it (maybe with an `sudo` at the front, depending on how it is configured).

**Comment by wrkzk** [comment]
I think this is definitely a NixOS specific issue, not an issue with mopidy-youtube. I tried it in a vm and it works with the new release.

**Comment by VergeDX** [comment]
Same issues on NixOS 21.05.

**Comment by 9acca9** [comment]
Hi.
Same problem in a raspbian bullseye.
`YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.
`
i make a sudo pip install mopidy-youtube and get this:
` sudo pip install mopidy-youtube
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: mopidy-youtube in /usr/local/lib/python3.9/dist-packages (3.6.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from mopidy-youtube) (2.25.1)
Requirement already satisfied: Pykka>=2.0.1 in /usr/lib/python3/dist-packages (from mopidy-youtube) (2.0.3)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.9/dist-packages (from mopidy-youtube) (4.11.1)
Requirement already satisfied: Mopidy>=3.1 in /usr/lib/python3/dist-packages (from mopidy-youtube) (3.4.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from mopidy-youtube) (52.0.0)
Requirement already satisfied: cachetools in /usr/local/lib/python3.9/dist-packages (from mopidy-youtube) (5.3.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.9/dist-packages (from beautifulsoup4->mopidy-youtube) (2.3.2.post1)
`
