### ISSUE TITLE
Help with config errors

### ISSUE THREAD

**Issue by Rhalah** [natumbri/mopidy-youtube#207]
Hello!
I'm trying to use Mopidy-youtube without success.
Followed instructions at github project page but get the error below after running "sudo mopidyctl config":

=================
[youtube]
enabled = false  ; Extension disabled due to config errors.
youtube_api_key = 
threads_max = 16
search_results = 15
playlist_max_videos = 20
api_enabled = false
autoplay_enabled = false
strict_autoplay = false
max_autoplay_length = 600
max_degrees_of_separation = 3
=================

I got the following warning after building Mopidy-youtube: 

"ytmusicapi 0.19.3 has requirement requests>=2.22, but you'll have requests 2.21.0 which is incompatible."

But that doesn't seem to be the problem.

How can I try to solve this?

**Comment by natumbri** [comment]
That's strange! The config looks fine to me - I'm not really sure where to start in terms of fixing this. Maybe have a look in the log for mopidy?

**Comment by Rhalah** [comment]
@natumbri:

Solved.
My fault. Sorry.
Extension enabled after I removed "allow_cache" config option.
