### ISSUE TITLE
Bandwidth throttling

### ISSUE THREAD

**Issue by thanxx** [natumbri/mopidy-youtube#208]
Hello, 

a few months back I started noticing that loading of some of the tracks takes forever and freezes down the Mopidy process until the download is finished. 
Just wanted to ask other users to comment here if they were facing the same issue when using this extension.

Googling led me to this issue https://github.com/ytdl-org/youtube-dl/issues/29326 , and as I understand the solution is to use **yt-dlp** https://github.com/yt-dlp/yt-dlp in order to bypass the limitation or wait for yt-dl will have a fix.

**Comment by pctablet505** [comment]
even yt-dlp is throttling now.

**Comment by natumbri** [comment]
#211 adds support for setting the ytdl package by a config option. Use  yt-dlp or any other youtube_dl compatible package you like.

Cheers
Nik
