### ISSUE TITLE
Stops playing songs for no apparent reason

### ISSUE THREAD

**Issue by mgrouch** [natumbri/mopidy-youtube#213]
There is an error in logs:

ERROR    [MainThread] mopidy.audio.gst GStreamer error: Forbidden

**Comment by TheEgghead27** [comment]
This has been an issue for me too, commenting to subscribe to any future developments on this thread

**Comment by natumbri** [comment]
Thanks both - without more information there's not much I can do. Is it happing for all videos or just one? How is your mopidy configured?

**Comment by TheEgghead27** [comment]
It is quite sporadic, I can queue up a YouTube playlist using the appropriate URL format, play a couple of songs, but after an undiscernible amount of time, the system freezes when it tries to change to the next track. It is possible to issue a skip command to jump over a freezing track and transition to the next one, but it still takes quite a while for the command to be processed. I will look into specific debug information; for now, I will just post my [config](https://github.com/natumbri/mopidy-youtube/files/7599538/mopidy.conf.txt).

Edit: I've actually been running mopidy for a while without the error occurring, potentially because I set `allow_cache = false` due to the mention of caching causing issues for #134, which was presumably fixed.

**Comment by Dzordzu** [comment]
Hi. Apparently it's a youtube-dl issue. The package has been abandoned. The fix is ready on the development branch. There you can pick either youtube-dl or yt-dlp (or anything that is yt-dl compatible) as the backend for the mopidy-youtube

**Comment by mgrouch** [comment]
> Hi. Apparently it's a youtube-dl issue. The package has been abandoned. The fix is ready on the development branch. There you can pick either youtube-dl or yt-dlp (or anything that is yt-dl compatible) as the backend for the mopidy-youtube

Where can we pick up the fix? What was changed and where? 

Thanks

**Comment by natumbri** [comment]
New release released.  If you wish to use an alternate youtube-dl library, in your configuration file you must install the package, (for eg. with pip) and set the youtube_dl_package option:
```
[youtube]
youtube_dl_package = [name] : alternative package to replace "youtube-dl"
```
Compatible (and possibly more up-to-date) libraries may include `yt-dlp` (https://github.com/yt-dlp/yt-dlp) and `youtube-dlc`.

Let me know if this doesn't fix the problem

**Comment by mgrouch** [comment]
I've done this:
```

sudo pip3 install --upgrade https://github.com/natumbri/mopidy-youtube/archive/develop.zip
sudo pip3 install yt-dlp


```

edited /etc/mopidy/mopidy.conf

to add 
```
`
youtube_dl_package = yt-dlp

`
```
into [youtube] section

then restarted
```

sudo systemctl stop mopidy
sudo systemctl start mopidy


```

And with 

`systemctl status mopidy`

I now see errors like this:

```

   Loaded: loaded (/lib/systemd/system/mopidy.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2021-12-22 04:19:30 GMT; 19s ago
  Process: 3738 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
  Process: 3739 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
 Main PID: 3740 (sh)
    Tasks: 22 (limit: 4180)
   CGroup: /system.slice/mopidy.service
           ├─3740 /usr/bin/sh -c c=0; r=1; while [ $c -lt 20 -a $r -ne 0 ] ; do ping -c 1 -n -w 1 spotify.com; r=$?; c=`expr $
           └─3748 /usr/bin/python3 /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Dec 22 04:19:39 lysmarine sh[3740]:     self.PyTubeCipher = Cipher(js=response.text)
Dec 22 04:19:39 lysmarine sh[3740]:   File "/usr/local/lib/python3.7/dist-packages/pytube/cipher.py", line 44, in __init__
Dec 22 04:19:39 lysmarine sh[3740]:     self.throttling_array = get_throttling_function_array(js)
Dec 22 04:19:39 lysmarine sh[3740]:   File "/usr/local/lib/python3.7/dist-packages/pytube/cipher.py", line 323, in get_throttl
Dec 22 04:19:39 lysmarine sh[3740]:     str_array = throttling_array_split(array_raw)
Dec 22 04:19:39 lysmarine sh[3740]:   File "/usr/local/lib/python3.7/dist-packages/pytube/parser.py", line 158, in throttling_
Dec 22 04:19:39 lysmarine sh[3740]:     match_start, match_end = match.span()
Dec 22 04:19:39 lysmarine sh[3740]: AttributeError: 'NoneType' object has no attribute 'span'
Dec 22 04:19:39 lysmarine sh[3740]: INFO     [Thread-4] mopidy_ytmusic YTMusic loaded 8 auto playlists sections
Dec 22 04:19:40 lysmarine sh[3740]: INFO     [Thread-4] mopidy_ytmusic YTMusic Auto Playlists refreshed in 1.99s

```

**Comment by mgrouch** [comment]
Stopped working completely:
```


Dec 22 04:26:32 lysmarine sh[3740]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/youtube.py", line 36, in wra
Dec 22 04:26:32 lysmarine sh[3740]:     func(self)  # should create the future
Dec 22 04:26:32 lysmarine sh[3740]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/youtube.py", line 333, in au
Dec 22 04:26:32 lysmarine sh[3740]:     youtube_dl = importlib.import_module(youtube_dl_package)
Dec 22 04:26:32 lysmarine sh[3740]:   File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
Dec 22 04:26:32 lysmarine sh[3740]:     return _bootstrap._gcd_import(name[level:], package, level)
Dec 22 04:26:32 lysmarine sh[3740]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Dec 22 04:26:32 lysmarine sh[3740]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Dec 22 04:26:32 lysmarine sh[3740]:   File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
Dec 22 04:26:32 lysmarine sh[3740]: ModuleNotFoundError: No module named 'yt-dlp'



```

**Comment by mgrouch** [comment]
Look like the line in config can't use dash (has to be underscore in package name)


`
youtube_dl_package = yt_dlp

`

**Comment by natumbri** [comment]
Thanks - yes, it has to be the package name, and the package name has an underscore.  I've made a slight edit to the README to make this a little clearer.  

All working for you, now?

**Comment by mgrouch** [comment]
So far so good. Time will show. Thanks
