### ISSUE TITLE
Not playing from playlist. Starts retrieving 4 seconds, then zeroes out and another 4 seconds

### ISSUE THREAD

**Issue by mgrouch** [natumbri/mopidy-youtube#214]
Not playing from playlist. Starts retrieving 4 seconds, then zeroes out and another 4 seconds
and continues that in a loop.
Doesn't play songs most of the attempts.
Not sure if it is yourtube-dl issue or something else.
There is no errors in a log in this case

**Comment by Dzordzu** [comment]
Probably a yt-dl issue. Check develop branch with a fix to this

```
youtube_dl_package = yt_dlp
```

**Comment by natumbri** [comment]
New release released.  If you wish to use an alternate youtube-dl library, in your configuration file you must install the package, (for eg. with pip) and set the youtube_dl_package option:
```
[youtube]
youtube_dl_package = [name] : alternative package to replace "youtube-dl"
```
Compatible (and possibly more up-to-date) libraries may include `yt-dlp` (https://github.com/yt-dlp/yt-dlp) and `youtube-dlc`.

Let me know if this doesn't fix the problem
