### ISSUE TITLE
Issue without the youtube_api_key

### ISSUE THREAD

**Issue by drodange** [natumbri/mopidy-youtube#215]
Hello, 
Writting this because i'm having some issues with mopidy-youtube when i'm not specifying the youtube_api_key.

In my mopidy config, i didn't change anything, except for youtube : 
[youtube]
enabled = true
channel_id = ( not working with any channel ID )
api_enabled = false

My issue come when i'm trying to go through the "youtube channel playlist" with ncmpcpp or with the frontend Iris
the main error is : 
Channel.list_channelplaylists error "" 

After that i tried to see what was happening in the code and specially in : mopidy_youtube/apis/youtube_japi.py
The issue seems to come from the " def traverse" which is raising the key error. 
I tried to use pdb set_trace to have an idea of what is happening, but didn't understand very well how the function TRAVERSE is working.
Maybe, this is just not suppose to work without the api_key ? 

Regards.

**Comment by natumbri** [comment]
Thanks for your report, and sorry to hear it is not working for you.  

You should be able to browse youtube channel playlists without a youtube_api_key - that is how I use mopidy-youtube, and it works just fine for me.  Can you give an example of a channel_id that does not work for you?

**Comment by drodange** [comment]
Thanks for the fast answering 

I tried with 3 or 4 channel id like for example : 

Blues & Jazz : UC9zktRjA2aI7cEZOfkDqmLg
Skillet : UCE8NoMFnai3tTuwdiQJ-78A

Both were returning the error : Channel.list_channelplaylists error ""

But, after enabling the api_key , it worked fine. ( I would prefer it to work without the key , but i can deal with it until i fix my issue ) 
Might be an issue with the number of playlist or something like that ?

**Comment by natumbri** [comment]
Thanks - yes, with those playlists, I get the same error. I will investigate!

Thanks again for raising and for following up with more info.

Cheers
Nik

**Comment by natumbri** [comment]
I made a new branch [fix/issue-215](/natumbri/mopidy-youtube/tree/fix/issue-215) - I think it is fixed. If you could test and report back, that would be great!

Cheers,
Nik

**Comment by drodange** [comment]
Hi, 
I just tested the fix/issue-215.
It now works fine for the channel_id I sent you before.

Thanks for the work.
Regards
