### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Dzordzu** [natumbri/mopidy-youtube#218]
Just a question, when a new release is planned to be published :)

Reasons:

* #213
* #214 
* Discussion under #160

**Comment by natumbri** [comment]
Yeah, I hear ya. Will try to get on it - busy time of year.

**Comment by Dzordzu** [comment]
Understandable. same here ;)

**Comment by mgrouch** [comment]
will

```

python3 -m pip install --upgrade https://github.com/natumbri/mopidy-youtube/archive/develop.zip


```

install above mentioned fixes?

Thanks

**Comment by natumbri** [comment]
New release released; not properly tested, so fingers crossed!
