### ISSUE TITLE
audio does not play when directly querying uri

### ISSUE THREAD

**Issue by natumbri** [natumbri/mopidy-youtube#22]
At https://github.com/mopidy/mopidy-youtube/issues/103#issuecomment-497909216 @sebsebmc reported:
>I tried both feature/implement-scrAPI and feature/proxy today by directly queuing a uri and the metadata seemed to load but the mopidy did not actually play the audio. I saw in the debug log that it entered the stop state at 0 seconds. Same behavior in both branches.

**Comment by natumbri** [comment]
@sebsebmc sorry to hear it isn't working for you.

Are you able to give any further details? Importantly, are you using it with the YouTube API enabled, what is the uri, and what front end are you using?

**Comment by sebsebmc** [comment]
I'm using a custom frontend https://github.com/aschmitz/spinner I installed both of those branches without making any config changes so I used the default settings.

Basically I have provided mopidy with the URI `yt:https://www.youtube.com/watch?v=DXLXsjXd3mI`
and here is the output of mopidy 
```
INFO     youtube LibraryProvider.lookup "yt:https://www.youtube.com/watch?v=DXLXsjXd3mI"
[youtube] DXLXsjXd3mI: Downloading webpage
[youtube] DXLXsjXd3mI: Downloading video info webpage
INFO     youtube PlaybackProvider.translate_uri "youtube:video/Arctic Monkeys - The Bakery full band studio version.DXLXsjXd3mI"
```
The metadata seems to have loaded fine. The length, title and image for the track loaded but there was no audio playing.

**Comment by natumbri** [comment]
Interesting. I tried mpc, as a kind of baseline.
`mpc add yt:https://www.youtube.com/watch?v=DXLXsjXd3mI` adds the track to the playlist and `mpc play` gets it going.

Could it be an issue with the front end? Are there instructions for installing the spinner front end you are using?

**Comment by sebsebmc** [comment]
Uh, documentation for spinner is definitely lacking. Its largely installing rails and then mopidy-gmusic is required as well. Searching for a `yt:` link short circuits the search and asks if you want to just play a youtube link.

Is there a requirement to send another play request to mopidy after the song is queued?

**Comment by natumbri** [comment]
I'm not sure what the intended behaviour of mopidy is...

**Comment by sebsebmc** [comment]
It seems that I was able to get it to play the audio, but it required issuing a play command after the translate URI happened. I'm not sure why mopidy-gmusic songs play just fine without having to send another play command but this seems to require it.

**Comment by sebsebmc** [comment]
Playing the same youtube track a second time worked without needing the extra play command. I'll have to get more info on whats happening. There's a chance it works perfectly some of the time.

**Comment by natumbri** [comment]
Thanks - I'll be interested to hear what you discover. It would be good to make the behaviour consistent! Maybe it has something to do with trying to play the file too early, the first time around?

**Comment by sebsebmc** [comment]
I wasn't able to reproduce the issue again... You can probably mark this closed now. Not sure why it wouldn't play before.

**Comment by natumbri** [comment]
Ok, will do. Thanks. 

The plugin really hasn't been tested very much - I've used it, and have incorporated the feedback that I have received, but I'm sure there are intermittent bugs lurking all over the place...
