### ISSUE TITLE
yt-dlp colors

### ISSUE THREAD

**Issue by drawanon** [natumbri/mopidy-youtube#226]
I found out, that using `yt-dlp` backend messes up the float parser

`[17181:YouTubeCoreListener-9] mopidy_youtube
  audio_url error could not convert string to float: '\x1b[0;94m  0.0\x1b[0m' (videoId: WGgEFoI9MhE)`

i think it's related to this line
https://github.com/natumbri/mopidy-youtube/blob/3fc5cc89081b4e58ad232233e5b9ac358cf7b775/mopidy_youtube/youtube.py#L357

my quick solution was to add `"no_color":True` to the `ytdl_options`, but i don't know if it's backward compatible with `youtube-dl` - i think it didn't have colored output
https://github.com/natumbri/mopidy-youtube/blob/3fc5cc89081b4e58ad232233e5b9ac358cf7b775/mopidy_youtube/youtube.py#L386

**Comment by natumbri** [comment]
fixed in v3.6; thanks.
