### ISSUE TITLE
Extension failed during setup

### ISSUE THREAD

**Issue by krtwastaken** [natumbri/mopidy-youtube#228]
Hello, I can't get the extension to work. I get this error in mopidy starting log:
```
May 25 16:26:52 vps-1c05f216 mopidy[4393]: ERROR    [MainThread] mopidy.__main__ Extension youtube failed during setup. This might have left the registry in a bad state.
May 25 16:26:52 vps-1c05f216 mopidy[4393]: Traceback (most recent call last):
May 25 16:26:52 vps-1c05f216 mopidy[4393]:   File "/usr/lib/python3/dist-packages/mopidy/__main__.py", line 129, in main
May 25 16:26:52 vps-1c05f216 mopidy[4393]:     extension.setup(registry)
May 25 16:26:52 vps-1c05f216 mopidy[4393]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/__init__.py", line 39, in setup
May 25 16:26:52 vps-1c05f216 mopidy[4393]:     from .backend import YouTubeBackend, YouTubeCoreListener
May 25 16:26:52 vps-1c05f216 mopidy[4393]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/backend.py", line 10, in <module>
May 25 16:26:52 vps-1c05f216 mopidy[4393]:     from mopidy_youtube.apis import youtube_api, youtube_japi, youtube_music
May 25 16:26:52 vps-1c05f216 mopidy[4393]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_youtube/apis/youtube_music.py", line 7, in <module>
May 25 16:26:52 vps-1c05f216 mopidy[4393]:     from ytmusicapi import YTMusic
May 25 16:26:52 vps-1c05f216 mopidy[4393]: ModuleNotFoundError: No module named 'ytmusicapi'

```
Giving my almost non-existent understanding of what I'm doing it's a miracle that I managed to get everything beside this to work. Can I get some help?

**Comment by natumbri** [comment]
Congratulations on getting that far. Looks like you need to install the `ytmusicapi` python module. Something like this should do it:
```
python3 -m pip install --upgrade ytmusicapi
```
Depending on your configuration, you may need to run that as administrator (eg with `sudo`).

Cheers
Nik

**Comment by krtwastaken** [comment]
Thank You, it works now. I thought installing this api is only required when I have music api enabled in the config so I didn't even think about installing it.

**Comment by natumbri** [comment]
Yes, I think you've found a problem that I should fix. The documentation suggests that `ytmusicapi` is only required when that API is enabled, but - as you have discovered - that's not actually what happens. 

I'm going to reopen this issue to remind me that this needs attention.

Thanks!
