### ISSUE TITLE
YT Playlists added in wrong order

### ISSUE THREAD

**Issue by jeremih** [natumbri/mopidy-youtube#233]
Hey! Really loving this extension, esp for single tracks.

However, I haven't been able to add a youtube playlist through this extension while preserving the playlist order. I have tried adding the same playlist to two different mopidy servers and both added the playlist with different, wrong orders. If this is a premium-only feature, please add that to the readme.

Thanks!

**Comment by jeremih** [comment]
Oh, seems I just needed to enable `ytmusicapi`.

**Comment by natumbri** [comment]
Thanks for the feedback - is it all working now?

If you like mopidy-youtube, you might be interested to check out https://github.com/natumbri/mopidy-tubeify - very much a personal project/work in progress, but it kinda works.

**Comment by jeremih** [comment]
Cool! I'll take note of that. Seems to be working fine now.
