### ISSUE TITLE
FR: Allow lookup of playlists using 'find' command

### ISSUE THREAD

**Issue by fatg3erman** [natumbri/mopidy-youtube#235]
Mopidy-Spotify used to accept the MPD command 

find file spotify:album:spotifyalbumid

to lookup an album uri and return the full track listing . It'd be great if I could do the same with a yt:playlist: Uri, otherwise all I can see for a lot of youtube music search results is something like 'Album: Album Name' which isn't very helpful when you're looking for a specific track.

**Comment by natumbri** [comment]
Interesting - can you give more details, and a working example, so I can play along at home?

**Comment by fatg3erman** [comment]
Hard to give an actual example because I cancelled my Spotify Premium subscription when they switched off libspotify, so here's one I made up:

```
search any Queen
file: spotify:album:blahblahblah
Time: 268
Artist: Queen
Album: Live Killers
AlbumArtist: Queen
Genre: Hard Rock
X-AlbumUri: spotify:album:blahblahblahblah
(etc - more albums and tracks)

```
As the writer of a Mopidy client that's not very useful. It's a an album that only has one "track", and when the user selects that track it actually adds the entire album to the play queue, which is not what the user expects and leads to a poor experience. but as the writer of a client, I can detect it and, when the user browses the album in my UI I can do

```
find file "spotify:album:blahblahblahblah"
file: spotify:track:uri_for_track_1
Time: 198
Artist: Queen
Album: Live Killers
Title: We Will Rock You
Date: 1979
Track: 1
AlbumArtist: Queen
Genre: Hard Rock
X-AlbumUri: spotify:album:blahblahblahblah
file: spotify:track:uri_fir_track_2
Time: 195
Artist: Queen
Album: Live Killers
Title: Let Me Entertain You
(etc etc)

```
and then I can show that to the user and they get a better experience and can select the tracks they want.

The analogous situation with mopidy-youtube is this kind of search result:

```
file: youtube:playlist:MPREb_UNDBPdpuLAS
Time: 0
Artist: YouTube Playlist (20 videos)
Album: On Air
Title: Album: On Air
Track: 0/20
AlbumArtist: YouTube Playlist (20 videos)
X-AlbumUri: youtube:playlist:MPREb_UNDBPdpuLAS

```
Where I'd need to 'find file' the youtube:playlist Uri to get the track listing (and if you start to support Youtube Music 'Albums' as :album: URis that'd be even better... )

**Comment by natumbri** [comment]
I'm not exactly sure what's required, but try this: 532874e93bf94a1a5f7c44aee83bbc22997dd2ef

**Comment by fatg3erman** [comment]
It works but it creates a new problem. 

When I look up the playlist, if it's a Youtube Music album it returns the correct artist (ie not 'YouTube Playlist (20 videos)') which means I can't associate it with the item in the UI.

It would be preferable if the initial search result returned the Artist info too, instead of 'YouTube Playlist (20 videos)'

**Comment by natumbri** [comment]
I think that can be fixed.

https://github.com/natumbri/mopidy-youtube/commit/35bc118d5f93d053d0322b8da2eeab592df48ebf

Probably need to do some testing, but seems ok.

**Comment by fatg3erman** [comment]
Yeah! So far that works beautifully. Thanks for the fast response!
