### ISSUE TITLE
So slooow

### ISSUE THREAD

**Issue by szuniverse** [natumbri/mopidy-youtube#24]
Hi.

First of all, great work.
But I use the HTTP JSON Api via mopidy I send this json:

``` json
{"method":"core.library.search","jsonrpc":"2.0","id":402,"params":{"query":{"any":["blink"]},"uris":["local:","spotify:","youtube:"]}}
```

And if I search on youtube its getting extremely slow, sometimes i never get a result..
But If I search without youtube everything works fast and always get result.

I use Rpi 2. and the latest modidy 1.0.0 and the latest mopdy-youtube version.

**Comment by jodal** [comment]
@dz0ny Any ideas what we can do here? Does pafy support timeouts or similar?

**Comment by szuniverse** [comment]
I think somehow the mopidy server should handle the timeout. Because it could happen with any other extension

**Comment by dz0ny** [comment]
Socket timeout is already at 600s, could it be just network issues? Btw each initial discovery for "track" consumes about 1MB. http://i.imgur.com/Ya9xMVd.png and is quite slow.

You can test yourself with mitmproxy+root cert:
```
env HTTPS_PROXY=http://localhost:8888 ytdl "https://www.youtube.com/watch?v=QnxpHIl5Ynw" -a
```

@szuniverse can you please start mopidy with 
```
# env pafydebug=1 mopidy
```
and do the same query that is slow to you.

**Comment by fopina** [comment]
Even though this is not active at the moment, I'd leave the note that using a process pool of 16 in underpowered low-core devices is one of the reasons to make it slower (and fail to retrieve results with youtube-dl).

In my RPi1 I've changed it to 2 processes only and it reduced to 1/5 of the time (from 3min to little over 30s), though still hard to use...

**Comment by Chateaudur** [comment]
Have you tried with [Kostas's PR](https://github.com/mopidy/mopidy-youtube/pull/46) about performance improvements? I want to test it but my SD card died on me last week...  That'd be good to have someone test it on Rpi1 :)
