### ISSUE TITLE
mopidy_youtube translate_uri error No module named yt-dlp

### ISSUE THREAD

**Issue by TRSx80** [natumbri/mopidy-youtube#252]
Thanks for maintaining this great project!  :beers: 

I had just installed Mopidy-YouTube and yt-dlp.  The latter I installed by downloading the single binary and making it executable.

I could search and browse ThemTube, but not play anything.  So I checked the logs and found the error in the title.

I searched Internet and did find #247 which was similar, and followed advice from there.

I first tried changing `yt-dlp` (in `youtube.youtube_dl_package` in `mopidy.conf`) back to `yt_dlp` but neither seemed to work (even after restarting, etc.).

Finally I `sudo python3 -m pip install --upgrade yt-dlp` (as you advised) which did work! [0]

I am not sure what to do about this (or even if anything can/should be done), but I thought I would at least report it.  Maybe it helps someone.

[0] Thankfully it didn't install too much crap, and also apparently pip does no longer allow wrecking distribution Python packages (a pleasant surprise!).

**Comment by natumbri** [comment]
Thanks for the feedback - yes, re `yt_dlp`, `mopidy_youtube` relies on the python module being available, so just installing an executable is probably not going to work.

Glad you got it working. What kind of system are you using it on?

**Comment by TRSx80** [comment]
This is on an ODROID-XU4, running Debian (Armbian).
