### ISSUE TITLE
Seeking skips the track

### ISSUE THREAD

**Issue by BrainStone** [natumbri/mopidy-youtube#28]
When seeking to a position the track gets skipped instead (tested with the feature/proxy branch)

**Comment by natumbri** [comment]
Are you able to give more details about your setup (which front end are you using)? And an example of a specific youtube video where it happens? Also, it would be good to know if the same behaviour happens with the official version.

Personally, I never seek, so I haven't seen this behavior.

Cheers
Nik

**Comment by BrainStone** [comment]
It happens with every frontend/MPD-client.

And a video this happens with is https://www.youtube.com/watch?v=qj5ZahqBfFE
Though it has happened with every one I tried so far.

And I honestly I don't want to be switching back and forth between the offical plugin and yours.

**Comment by natumbri** [comment]
Thanks. 

Honestly, neither do I, and this bug doesn't affect me (and hasn't motivated anyone else to raise it), so it might be a long time before I look at it. 

The more prepared you are to assist, the more motivated I'll be to look for a fix.

**Comment by BrainStone** [comment]
I mean what else could I do besides check if it happens the original plugin as well?

**Comment by natumbri** [comment]
Seems this is a known issue https://github.com/mopidy/mopidy-youtube/issues/34

**Comment by natumbri** [comment]
Closed by #40 I assume
