### ISSUE TITLE
Certifcate error on youtube-dl download

### ISSUE THREAD

**Issue by Poeschl** [natumbri/mopidy-youtube#36]
To implement https://github.com/Poeschl/Hassio-Addons/issues/22 I installed the development branch with `pip install https://github.com/natumbri/mopidy-youtube/archive/develop.zip` inside a docker container.

Search on youtube works fine. But the logs shows certificate errors on downloading the video. Log output:

```
INFO     youtube LibraryProvider.search "{u'any': [u'Final Space']}"
INFO     Searching YouTube for query "Final Space"
INFO     session.get triggered: search
INFO     youtube LibraryProvider.search "{u'album': [u'Final Space']}"
INFO     youtube LibraryProvider.search "{u'artist': [u'Final Space']}"
INFO     youtube LibraryProvider.lookup "youtube:video/Final Space OFFICIAL TRAILER Series Premiere February 26 TBS.4EHbt_kSkG8"
INFO     youtube PlaybackProvider.translate_uri "youtube:video/Final Space OFFICIAL TRAILER Series Premiere February 26 TBS.4EHbt_kSkG8"
[youtube] 4EHbt_kSkG8: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))
ERROR    audio_url error "ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))"
WARNING  Track is not playable: youtube:video/Final Space OFFICIAL TRAILER Series Premiere February 26 TBS.4EHbt_kSkG8
```

Already tried to update the installed certificates but no luck. Any idea or solutions?

**Comment by natumbri** [comment]
Thanks for the report. That's not something I've ever seen before. Are you able to post the YouTube section of your mopidy.conf? Also, is it failing for everything, or just some searches? And what front end are you using?

**Comment by natumbri** [comment]
One way to avoid this problem ever arising might be to not bother checking SSL certificates?  If you're happy to give that a try, try this: 

`pip install https://github.com/natumbri/mopidy-youtube/archive/fix/ssl-certificate-error.zip`

The change is here: https://github.com/natumbri/mopidy-youtube/commit/58396bee70e9a686d3ef5dd8ad48af74974fb4d2

Doesn't explain what is causing the problem.  Some kind of misconfiguration in the container would be my (based on nothing much) guess.  Is the date set correctly?

**Comment by Poeschl** [comment]
Morning 😅
I just noticed that I have set no config at all. So I assume it's all the default values. 

I'm using the `iris` frontend for interactions. I will check the time when close to my machine. But I assume it should be set correctly since apt hadn't any problem resolving its packages. 

I guess to ignore the certificates will work, will try it and also continue to search for a solution as well 😉

Maybe the ignore certificates can be a flag for the plugin?

**Comment by Poeschl** [comment]
Test results:
* date correctly set
* ca-certificates up to date
* openssl existing
* `curl -vv <any youtube url>` verifies the tls certificate correctly
* updated certifi for finding the certificate with python

But no luck on the certificate way.

The `--no-check-certificate` way works but seems kind of dirty for me. :sweat: 

The installed packages are listed here: [Dockerfile](https://github.com/Poeschl/Hassio-Addons/blob/mopidy-update/mopidy/Dockerfile)

**Comment by natumbri** [comment]
Maybe try this and see if it changes anything?
https://github.com/Poeschl/Hassio-Addons/commit/8a342417c1efdc93100e4a8a0b59ca7e62150131

**Comment by Poeschl** [comment]
I removed the complete `remove wget gnupg` with no change on the result.
I will take some research on it, but for now can we go with an flag which triggers the `no-check` flag?

**Comment by natumbri** [comment]
I'll just make the no certificate thing permanent, for now. It is a bit of a hack, but I don't see much downside.
