### ISSUE TITLE
requests-cache breaks other backends

### ISSUE THREAD

**Issue by fatg3erman** [natumbri/mopidy-youtube#37]
I've been having a issue where some other backends that use the requests module had stopped working properly. I tracked it down to the fact that mopidy-youtube is creating a cache using requests-cache. This cache is global and as such it breaks the functionality of all other backends that use web requests (which is a great many of them).

There are other caching options available but it seems to me it's easier just to disable it.

**Comment by natumbri** [comment]
Agree. I've actually been meaning to remove it anyway - it doesn't really seem to improve performance in ordinary use situations. 

Thanks for raising the issue.
