### ISSUE TITLE
pafy vs youtube-dl

### ISSUE THREAD

**Issue by jodal** [natumbri/mopidy-youtube#41]
pafy >0.3.74 has started depending on youtube-dl. Should we use youtube-dl directly instead of pafy?

**Comment by dz0ny** [comment]
Last time I checked youtube-dl had awful interface for getting raw data,  but if we use it directly we can support many more providers. :)

**Comment by AndreMiras** [comment]
Would you be interested in a pull request migrating to youtube-dl?

**Comment by raneri** [comment]
The commit by Jacek Szafarkiewicz works flawlessy. Solved unplayability with Pafy, for me (on Raspberry PI3).
