### ISSUE TITLE
Add support for exact search

### ISSUE THREAD

**Issue by ysamlan** [natumbri/mopidy-youtube#49]
Using Mopidy 1.1.1 and mopidy-youtube 2.0.1 on a Raspberry Pi running Raspbian Jessie and using musicbox_webclient. Searches return no result; verbose logs show:

```
INFO     2015-10-22 20:12:27,413 [8435:YouTubeBackend-7] mopidy_youtube
  Searching YouTube for query 'hello'
INFO     2015-10-22 20:12:27,431 [8435:YouTubeBackend-7] requests.packages.urllib3.connectionpool
  Starting new HTTPS connection (1): www.googleapis.com
WARNING  2015-10-22 20:12:33,097 [8435:Core-11] mopidy.core.library
  YouTubeBackend does not implement library.search() with "exact" support. Please upgrade it.
```

**Comment by jodal** [comment]
Why did you close the issue?

**Comment by ysamlan** [comment]
It stopped happening to me - may have just been a temporary fluke, or something specific to the version of musicbox_webclient I was using at the time. I'd been fiddling with quite a few settings so I'm not sure exactly what changed it, though - if I manage to repro, I'll reopen this.

**Comment by onewalles** [comment]
This issue is still present - I can reproduce it every time with the same setup (Mopidy 1.1.1 and mopidy-youtube 2.0.1 on a Raspberry Pi running Raspbian Jessie and using musicbox_webclient). It also happens when using other webclients (eg. mopidy-moped).

**Comment by Crowdedlight** [comment]
Having the same error as described. At a restart/reinstall it worked fine with searching. But after I restarted the mopidy server I was back to the error.

Not sure what made it work at some point. Will keep trying some stuff to see if I can find it
