### ISSUE TITLE
Direct YouTube URIs don’t return in expected results

### ISSUE THREAD

**Issue by AskMP** [natumbri/mopidy-youtube#60]
I’ve seen a similar issue in a closed issue but there was no solution posted and the link to the bug fix that was supposed to resolve it has already been implemented.

I’ve attempting to search via various methods; yt: within the search field, ['youtube:']: as the {search}.uris etc… and although is absolutely searches YouTube, the result is never what is expected. As an example:
I’m attempting to track down specifically https://www.youtube.com/watch?v=BXpdmKELE1k
Searching for it using “Swedish House Mafia - Save The World” and “Swedish House Mafia - Save The World SHMVEVO” (the addition of it uploader) results in 5 items but none of which are the expected on.
Searching for “BXpdmKELE1k” or the full link results in some Digimon song… completely incorrect.

Another example of this is https://www.youtube.com/watch?v=ukNOaKeUEQY where the URL and video ID result in “I’m a hipster” (granted, somewhat relevant if you know the band but beside the point)

As for versions, all are latest and the only bizarre thing that may be different is I’ve manually updated the “backend_internal.py” for that most recent “unquote_plus” issue since the force update of pafy didn’t change it.

**Comment by AskMP** [comment]
Have you been able to look into this at all?

**Comment by natumbri** [comment]
Mopidy 3 / Mopidy-Youtube 3 (using bs4 backend):

- first hit on search for “Swedish House Mafia - Save The World”  or “BXpdmKELE1k” is youtube:video/Swedish House Mafia - Save The World (Official Video).BXpdmKELE1k

- first hit on search for "https://www.youtube.com/watch?v=ukNOaKeUEQY" is youtube:video/San Cisco - Awkward.ukNOaKeUEQY

I assume those search results are all as expected, so closing issue.
