### ISSUE TITLE
Unintended behaviour when browsing ncmpcpp media library with mopidy-youtube

### ISSUE THREAD

**Issue by Eirikep** [natumbri/mopidy-youtube#65]
Hi,

The media library in ncmpcpp works great with mopidy-spotify, but not so well when also mopidy-youtube is enabled. As an example, when I try to explore the artist Serengeti's album "Be a Man", the mopidy output is the following: 

INFO     Searching Spotify for: album:"Be a Man" artist:"Serengeti"
INFO     Searching YouTube for query 'Be a Man'

Obviously, the Spotify search is correct, while the Youtube search yields a bunch of results that are completely irrelevant and that makes it inconvenient to quickly and easily add the album to my current playlist (instead I am forced to mark the Spotify results and avoid the Youtube ones). It seems to me that a better solution would simply be to disable Youtube searching when this particular functionality is used (though I have no idea how easy/hard this would be to do).

I appreciate a lot the possibility to search for Youtube videos in the ncmcpcc search engine, but right now it seems like I have to choose between this or the media library feature. Hopefully it will be possible to have both.

**Comment by john-bonachon** [comment]
Any news on how to handle this?

**Comment by natumbri** [comment]
Hi @john-bonachon - have you tried the new mopidy-youtube extension? Is this still an issue?
