### ISSUE TITLE
Show Album Show Artist and List Divider shouldn't show up

### ISSUE THREAD

**Issue by lulu3000** [natumbri/mopidy-youtube#67]
In playlists, there is the list divider "Youtube" which pretends youtube to be an album. When clicked, it leads into nirvana. Equally, the pop-ups show "Show Album YouTube" and "Show Artist YouTube" which make no sense and do not work. All this could maybe just discarded, like other stream extensions like SomaFM do.
I will look for it in deapth when I have the time. At the moment, I just commented it out locally for all tracks, since I don't use it - too many features confuse the user and musicbox doesn't have to replace google, in my opinion. 

Generally: The extension is so wonderful, thank you all!

**Comment by natumbri** [comment]
@lulu3000 is this still a problem? If so, would you mind spelling it out in a bit more detail?
