### ISSUE TITLE
GStreamer warning: gst-stream-error-quark: No volume control found (3)

### ISSUE THREAD

**Issue by jobe451** [natumbri/mopidy-youtube#73]
When I try to play a yt: link, the player downloads the corresponding picture, the timer starts counting, but I can't hear any sound. On the console I get:
WARNING  GStreamer warning: gst-stream-error-quark: No volume control found (3)

I can play musik from "local" successfully.

**Comment by jalvarezpiedra** [comment]
Hi, did you find a solution?
I have the same problem on my Raspberry PI 3

**Comment by rahulonmars** [comment]
Any solution?

**Comment by natumbri** [comment]
@jobe451, @jalvarezpiedra, @rahulonmars, @dflvunoooooo is this still a problem or can I close the issue?

**Comment by rahulonmars** [comment]
> @jobe451, @jalvarezpiedra, @rahulonmars, @dflvunoooooo is this still a problem or can I close the issue?

Hey,
I'm not using this on raspberry pi anymore. So no issues from my side.
Thanks for your time.

**Comment by natumbri** [comment]
Thanks @rahulonmars - I'm closing this one.
