### ISSUE TITLE
Unknown url type

### ISSUE THREAD

**Issue by matit97** [natumbri/mopidy-youtube#78]
Hi,

i got this error when i try to search in Mopidy for a titel:

INFO     Starting Mopidy backends: TuneInBackend, YouTubeBackend, StreamBackend,                                       M3UBackend, FileBackend, SoundCloudBackend, SpotifyTunigoBackend, SpotifyBacken                                     d
INFO     Audio output set to "autoaudiosink"
INFO     Starting Mopidy core
INFO     Logged in to Spotify in offline mode
INFO     Logged in to Spotify in online mode
INFO     Starting Mopidy frontends: TtsGpio, HttpFrontend
INFO     Starting GLib mainloop
INFO     HTTP server running at [::ffff:192.168.178.39]:6680
INFO     Searching Spotify for: "beat it"
INFO     Searching YouTube for query 'beat it'
INFO     Searching SoundCloud for: beat it
INFO     unknown url type: /yts/jsbin/player-de_DE-vflFKX8cc/base.js
INFO     unknown url type: /yts/jsbin/player-de_DE-vflFKX8cc/base.js
INFO     unknown url type: /yts/jsbin/player-de_DE-vflFKX8cc/base.js
INFO     unknown url type: /yts/jsbin/player-de_DE-vflFKX8cc/base.js
INFO     unknown url type: /yts/jsbin/player-de_DE-vflFKX8cc/base.js
INFO     unknown url type: /yts/jsbin/player-de_DE-vflFKX8cc/base.js
INFO     unknown url type: /yts/jsbin/player-de_DE-vflFKX8cc/base.js
INFO     unknown url type: /yts/jsbin/player-de_DE-vflFKX8cc/base.js
INFO     unknown url type: /yts/jsbin/player-de_DE-vflFKX8cc/base.js
INFO     unknown url type: /yts/jsbin/player-de_DE-vflFKX8cc/base.js

Running mopidy on a Rasperry Pi. Please help me. :)

**Comment by reconmaster** [comment]
I can confirm this bug. I think it may be due to a recent change in youtube script as alluded to in the youtube-dl bug [report](https://github.com/rg3/youtube-dl/issues/11894). While I can get some functionality, the error keeps causing some connection grief to clients.

**Comment by valerius21** [comment]
Same issue. pls fix

**Comment by kingosticks** [comment]
Have you tried upgrading youtube-dl? That would be my first suggestion.

**Comment by EpicDJL** [comment]
Same issue

**Comment by Dubzie** [comment]
I've upgraded my youtube-dl

Aug 04 14:45:53 MusicBox mopidy[868]: INFO     unknown url type: /yts/jsbin/player-vfl8KhWdC/en_US/base.js
Aug 04 14:45:53 MusicBox mopidy[868]: INFO     unknown url type: /yts/jsbin/player-vfl8KhWdC/en_US/base.js
Aug 04 14:45:53 MusicBox mopidy[868]: INFO     unknown url type: /yts/jsbin/player-vfl8KhWdC/en_US/base.js
Aug 04 14:45:53 MusicBox mopidy[868]: INFO     unknown url type: /yts/jsbin/player-vfl8KhWdC/en_US/base.js
Aug 04 14:45:54 MusicBox mopidy[868]: INFO     unknown url type: /yts/jsbin/player-vfl8KhWdC/en_US/base.js
Aug 04 14:45:54 MusicBox mopidy[868]: INFO     unknown url type: /yts/jsbin/player-vfl8KhWdC/en_US/base.js
Aug 04 14:45:54 MusicBox mopidy[868]: INFO     unknown url type: /yts/jsbin/player-vfl8KhWdC/en_US/base.js
Aug 04 14:45:54 MusicBox mopidy[868]: INFO     unknown url type: /yts/jsbin/player-vfl8KhWdC/en_US/base.js
Aug 04 14:45:54 MusicBox mopidy[868]: INFO     unknown url type: /yts/jsbin/player-vfl8KhWdC/en_US/base.js
Aug 04 14:45:54 MusicBox mopidy[868]: INFO     unknown url type: /yts/jsbin/player-vfl8KhWdC/en_US/base.js

**Comment by Hugomm** [comment]
Same issue here

**Comment by protecto** [comment]
I had the same problem and discovered that YouTube urls that had '-' character were problematic.

Installing youtube-dl for python2 fixed this for me.

```python
pip2 install youtube-dl
```

**Comment by Dubzie** [comment]
"Requirement already satisfied: youtube-dl in /usr/local/lib/python2.7/dist-packages" still have this issue.

**Comment by kingosticks** [comment]
Do you have the very latest version of the package?

**Comment by Dubzie** [comment]
youtube-dl-2017.8.13
